// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package tournaments

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipantPoints = `-- name: AddParticipantPoints :one
UPDATE tournament_participants SET points = points + $1::int WHERE id = $2
RETURNING id, tournament_id, user_id, guest_name, deck_id, commander_name, points, created_at
`

type AddParticipantPointsParams struct {
	Delta int32       `json:"delta"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) AddParticipantPoints(ctx context.Context, arg AddParticipantPointsParams) (TournamentParticipant, error) {
	row := q.db.QueryRow(ctx, addParticipantPoints, arg.Delta, arg.ID)
	var i TournamentParticipant
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.UserID,
		&i.GuestName,
		&i.DeckID,
		&i.CommanderName,
		&i.Points,
		&i.CreatedAt,
	)
	return i, err
}

const advanceTournamentRound = `-- name: AdvanceTournamentRound :one
UPDATE tournaments SET current_round = current_round + 1 WHERE id = $1 RETURNING id, organizer_id, name, format, target_players, status, round_count, current_round, join_code, created_at, started_at, finished_at
`

func (q *Queries) AdvanceTournamentRound(ctx context.Context, id pgtype.UUID) (Tournament, error) {
	row := q.db.QueryRow(ctx, advanceTournamentRound, id)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Format,
		&i.TargetPlayers,
		&i.Status,
		&i.RoundCount,
		&i.CurrentRound,
		&i.JoinCode,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const countParticipants = `-- name: CountParticipants :one
SELECT COUNT(*)::int FROM tournament_participants WHERE tournament_id = $1
`

func (q *Queries) CountParticipants(ctx context.Context, tournamentID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countParticipants, tournamentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnrecordedSeatsInRound = `-- name: CountUnrecordedSeatsInRound :one
SELECT COUNT(*)::int FROM tournament_table_seats tts
JOIN tournament_tables tt ON tt.id = tts.tournament_table_id
WHERE tt.tournament_round_id = $1 AND tts.finish_position IS NULL
`

func (q *Queries) CountUnrecordedSeatsInRound(ctx context.Context, tournamentRoundID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnrecordedSeatsInRound, tournamentRoundID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO tournament_participants (tournament_id, user_id, guest_name, deck_id, commander_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tournament_id, user_id, guest_name, deck_id, commander_name, points, created_at
`

type CreateParticipantParams struct {
	TournamentID  pgtype.UUID `json:"tournament_id"`
	UserID        pgtype.UUID `json:"user_id"`
	GuestName     pgtype.Text `json:"guest_name"`
	DeckID        pgtype.UUID `json:"deck_id"`
	CommanderName pgtype.Text `json:"commander_name"`
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (TournamentParticipant, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.TournamentID,
		arg.UserID,
		arg.GuestName,
		arg.DeckID,
		arg.CommanderName,
	)
	var i TournamentParticipant
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.UserID,
		&i.GuestName,
		&i.DeckID,
		&i.CommanderName,
		&i.Points,
		&i.CreatedAt,
	)
	return i, err
}

const createRound = `-- name: CreateRound :one
INSERT INTO tournament_rounds (tournament_id, round_number)
VALUES ($1, $2)
RETURNING id, tournament_id, round_number, status, created_at, finished_at
`

type CreateRoundParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	RoundNumber  int32       `json:"round_number"`
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (TournamentRound, error) {
	row := q.db.QueryRow(ctx, createRound, arg.TournamentID, arg.RoundNumber)
	var i TournamentRound
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RoundNumber,
		&i.Status,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createTable = `-- name: CreateTable :one
INSERT INTO tournament_tables (tournament_round_id, table_number)
VALUES ($1, $2)
RETURNING id, tournament_round_id, table_number
`

type CreateTableParams struct {
	TournamentRoundID pgtype.UUID `json:"tournament_round_id"`
	TableNumber       int32       `json:"table_number"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (TournamentTable, error) {
	row := q.db.QueryRow(ctx, createTable, arg.TournamentRoundID, arg.TableNumber)
	var i TournamentTable
	err := row.Scan(&i.ID, &i.TournamentRoundID, &i.TableNumber)
	return i, err
}

const createTableSeat = `-- name: CreateTableSeat :one
INSERT INTO tournament_table_seats (tournament_table_id, tournament_participant_id)
VALUES ($1, $2)
RETURNING id, tournament_table_id, tournament_participant_id, finish_position, points_awarded
`

type CreateTableSeatParams struct {
	TournamentTableID       pgtype.UUID `json:"tournament_table_id"`
	TournamentParticipantID pgtype.UUID `json:"tournament_participant_id"`
}

func (q *Queries) CreateTableSeat(ctx context.Context, arg CreateTableSeatParams) (TournamentTableSeat, error) {
	row := q.db.QueryRow(ctx, createTableSeat, arg.TournamentTableID, arg.TournamentParticipantID)
	var i TournamentTableSeat
	err := row.Scan(
		&i.ID,
		&i.TournamentTableID,
		&i.TournamentParticipantID,
		&i.FinishPosition,
		&i.PointsAwarded,
	)
	return i, err
}

const createTournament = `-- name: CreateTournament :one
INSERT INTO tournaments (organizer_id, name, target_players, join_code)
VALUES ($1, $2, $3, $4)
RETURNING id, organizer_id, name, format, target_players, status, round_count, current_round, join_code, created_at, started_at, finished_at
`

type CreateTournamentParams struct {
	OrganizerID   pgtype.UUID `json:"organizer_id"`
	Name          string      `json:"name"`
	TargetPlayers pgtype.Int4 `json:"target_players"`
	JoinCode      string      `json:"join_code"`
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, createTournament,
		arg.OrganizerID,
		arg.Name,
		arg.TargetPlayers,
		arg.JoinCode,
	)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Format,
		&i.TargetPlayers,
		&i.Status,
		&i.RoundCount,
		&i.CurrentRound,
		&i.JoinCode,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteParticipantsForTournament = `-- name: DeleteParticipantsForTournament :exec
DELETE FROM tournament_participants WHERE tournament_id = $1
`

// Only needed to delete a tournament still in 'registration': rounds/tables/seats
// don't exist yet at that point (StartTournament is what creates the first ones),
// so participants are the only rows referencing it. See service.DeleteTournament.
func (q *Queries) DeleteParticipantsForTournament(ctx context.Context, tournamentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteParticipantsForTournament, tournamentID)
	return err
}

const deleteTournament = `-- name: DeleteTournament :exec
DELETE FROM tournaments WHERE id = $1
`

func (q *Queries) DeleteTournament(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTournament, id)
	return err
}

const finishRound = `-- name: FinishRound :one
UPDATE tournament_rounds SET status = 'finished', finished_at = now() WHERE id = $1 RETURNING id, tournament_id, round_number, status, created_at, finished_at
`

func (q *Queries) FinishRound(ctx context.Context, id pgtype.UUID) (TournamentRound, error) {
	row := q.db.QueryRow(ctx, finishRound, id)
	var i TournamentRound
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RoundNumber,
		&i.Status,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishTournament = `-- name: FinishTournament :one
UPDATE tournaments SET status = 'finished', finished_at = now() WHERE id = $1 RETURNING id, organizer_id, name, format, target_players, status, round_count, current_round, join_code, created_at, started_at, finished_at
`

func (q *Queries) FinishTournament(ctx context.Context, id pgtype.UUID) (Tournament, error) {
	row := q.db.QueryRow(ctx, finishTournament, id)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Format,
		&i.TargetPlayers,
		&i.Status,
		&i.RoundCount,
		&i.CurrentRound,
		&i.JoinCode,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, tournament_id, user_id, guest_name, deck_id, commander_name, points, created_at FROM tournament_participants WHERE id = $1 LIMIT 1
`

func (q *Queries) GetParticipant(ctx context.Context, id pgtype.UUID) (TournamentParticipant, error) {
	row := q.db.QueryRow(ctx, getParticipant, id)
	var i TournamentParticipant
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.UserID,
		&i.GuestName,
		&i.DeckID,
		&i.CommanderName,
		&i.Points,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipantByUser = `-- name: GetParticipantByUser :one
SELECT tp.id, tp.tournament_id, tp.user_id, tp.guest_name, tp.deck_id, tp.commander_name,
       tp.points, tp.created_at,
       u.username AS username, d.name AS deck_name, d.commander AS deck_commander
FROM tournament_participants tp
LEFT JOIN users u ON u.id = tp.user_id
LEFT JOIN decks d ON d.id = tp.deck_id
WHERE tp.tournament_id = $1 AND tp.user_id = $2
LIMIT 1
`

type GetParticipantByUserParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

type GetParticipantByUserRow struct {
	ID            pgtype.UUID      `json:"id"`
	TournamentID  pgtype.UUID      `json:"tournament_id"`
	UserID        pgtype.UUID      `json:"user_id"`
	GuestName     pgtype.Text      `json:"guest_name"`
	DeckID        pgtype.UUID      `json:"deck_id"`
	CommanderName pgtype.Text      `json:"commander_name"`
	Points        int32            `json:"points"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	Username      pgtype.Text      `json:"username"`
	DeckName      pgtype.Text      `json:"deck_name"`
	DeckCommander pgtype.Text      `json:"deck_commander"`
}

func (q *Queries) GetParticipantByUser(ctx context.Context, arg GetParticipantByUserParams) (GetParticipantByUserRow, error) {
	row := q.db.QueryRow(ctx, getParticipantByUser, arg.TournamentID, arg.UserID)
	var i GetParticipantByUserRow
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.UserID,
		&i.GuestName,
		&i.DeckID,
		&i.CommanderName,
		&i.Points,
		&i.CreatedAt,
		&i.Username,
		&i.DeckName,
		&i.DeckCommander,
	)
	return i, err
}

const getRound = `-- name: GetRound :one
SELECT id, tournament_id, round_number, status, created_at, finished_at FROM tournament_rounds WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRound(ctx context.Context, id pgtype.UUID) (TournamentRound, error) {
	row := q.db.QueryRow(ctx, getRound, id)
	var i TournamentRound
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RoundNumber,
		&i.Status,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRoundByNumber = `-- name: GetRoundByNumber :one
SELECT id, tournament_id, round_number, status, created_at, finished_at FROM tournament_rounds WHERE tournament_id = $1 AND round_number = $2 LIMIT 1
`

type GetRoundByNumberParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	RoundNumber  int32       `json:"round_number"`
}

func (q *Queries) GetRoundByNumber(ctx context.Context, arg GetRoundByNumberParams) (TournamentRound, error) {
	row := q.db.QueryRow(ctx, getRoundByNumber, arg.TournamentID, arg.RoundNumber)
	var i TournamentRound
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.RoundNumber,
		&i.Status,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getTable = `-- name: GetTable :one
SELECT id, tournament_round_id, table_number FROM tournament_tables WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTable(ctx context.Context, id pgtype.UUID) (TournamentTable, error) {
	row := q.db.QueryRow(ctx, getTable, id)
	var i TournamentTable
	err := row.Scan(&i.ID, &i.TournamentRoundID, &i.TableNumber)
	return i, err
}

const getTableForParticipantInRound = `-- name: GetTableForParticipantInRound :one
SELECT tt.id, tt.tournament_round_id, tt.table_number FROM tournament_tables tt
JOIN tournament_table_seats tts ON tts.tournament_table_id = tt.id
WHERE tt.tournament_round_id = $1 AND tts.tournament_participant_id = $2
LIMIT 1
`

type GetTableForParticipantInRoundParams struct {
	TournamentRoundID       pgtype.UUID `json:"tournament_round_id"`
	TournamentParticipantID pgtype.UUID `json:"tournament_participant_id"`
}

func (q *Queries) GetTableForParticipantInRound(ctx context.Context, arg GetTableForParticipantInRoundParams) (TournamentTable, error) {
	row := q.db.QueryRow(ctx, getTableForParticipantInRound, arg.TournamentRoundID, arg.TournamentParticipantID)
	var i TournamentTable
	err := row.Scan(&i.ID, &i.TournamentRoundID, &i.TableNumber)
	return i, err
}

const getTournament = `-- name: GetTournament :one
SELECT id, organizer_id, name, format, target_players, status, round_count, current_round, join_code, created_at, started_at, finished_at FROM tournaments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTournament(ctx context.Context, id pgtype.UUID) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournament, id)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Format,
		&i.TargetPlayers,
		&i.Status,
		&i.RoundCount,
		&i.CurrentRound,
		&i.JoinCode,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getTournamentByJoinCode = `-- name: GetTournamentByJoinCode :one
SELECT id, organizer_id, name, format, target_players, status, round_count, current_round, join_code, created_at, started_at, finished_at FROM tournaments WHERE join_code = $1 LIMIT 1
`

func (q *Queries) GetTournamentByJoinCode(ctx context.Context, joinCode string) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournamentByJoinCode, joinCode)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Format,
		&i.TargetPlayers,
		&i.Status,
		&i.RoundCount,
		&i.CurrentRound,
		&i.JoinCode,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listEnrichedSeatsForTable = `-- name: ListEnrichedSeatsForTable :many
SELECT
  tts.id AS seat_id, tts.tournament_participant_id, tts.finish_position, tts.points_awarded,
  tp.user_id, tp.guest_name, tp.commander_name AS participant_commander_name,
  u.username, d.name AS deck_name, d.commander AS deck_commander
FROM tournament_table_seats tts
JOIN tournament_participants tp ON tp.id = tts.tournament_participant_id
LEFT JOIN users u ON u.id = tp.user_id
LEFT JOIN decks d ON d.id = tp.deck_id
WHERE tts.tournament_table_id = $1
ORDER BY tp.points DESC
`

type ListEnrichedSeatsForTableRow struct {
	SeatID                   pgtype.UUID `json:"seat_id"`
	TournamentParticipantID  pgtype.UUID `json:"tournament_participant_id"`
	FinishPosition           pgtype.Int4 `json:"finish_position"`
	PointsAwarded            int32       `json:"points_awarded"`
	UserID                   pgtype.UUID `json:"user_id"`
	GuestName                pgtype.Text `json:"guest_name"`
	ParticipantCommanderName pgtype.Text `json:"participant_commander_name"`
	Username                 pgtype.Text `json:"username"`
	DeckName                 pgtype.Text `json:"deck_name"`
	DeckCommander            pgtype.Text `json:"deck_commander"`
}

// Same enrichment as ListSeatsForRound, scoped to a single table (used to
// render the response right after RecordTableResult, without re-fetching the
// whole round).
func (q *Queries) ListEnrichedSeatsForTable(ctx context.Context, tournamentTableID pgtype.UUID) ([]ListEnrichedSeatsForTableRow, error) {
	rows, err := q.db.Query(ctx, listEnrichedSeatsForTable, tournamentTableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrichedSeatsForTableRow
	for rows.Next() {
		var i ListEnrichedSeatsForTableRow
		if err := rows.Scan(
			&i.SeatID,
			&i.TournamentParticipantID,
			&i.FinishPosition,
			&i.PointsAwarded,
			&i.UserID,
			&i.GuestName,
			&i.ParticipantCommanderName,
			&i.Username,
			&i.DeckName,
			&i.DeckCommander,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsForTournament = `-- name: ListParticipantsForTournament :many
SELECT tp.id, tp.tournament_id, tp.user_id, tp.guest_name, tp.deck_id, tp.commander_name,
       tp.points, tp.created_at,
       u.username AS username, d.name AS deck_name, d.commander AS deck_commander
FROM tournament_participants tp
LEFT JOIN users u ON u.id = tp.user_id
LEFT JOIN decks d ON d.id = tp.deck_id
WHERE tp.tournament_id = $1
ORDER BY tp.points DESC, tp.created_at ASC
`

type ListParticipantsForTournamentRow struct {
	ID            pgtype.UUID      `json:"id"`
	TournamentID  pgtype.UUID      `json:"tournament_id"`
	UserID        pgtype.UUID      `json:"user_id"`
	GuestName     pgtype.Text      `json:"guest_name"`
	DeckID        pgtype.UUID      `json:"deck_id"`
	CommanderName pgtype.Text      `json:"commander_name"`
	Points        int32            `json:"points"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	Username      pgtype.Text      `json:"username"`
	DeckName      pgtype.Text      `json:"deck_name"`
	DeckCommander pgtype.Text      `json:"deck_commander"`
}

// Standings order: most points first, registration order breaks ties (see
// pairing.go's doc for why no fancier tiebreaker is computed).
func (q *Queries) ListParticipantsForTournament(ctx context.Context, tournamentID pgtype.UUID) ([]ListParticipantsForTournamentRow, error) {
	rows, err := q.db.Query(ctx, listParticipantsForTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantsForTournamentRow
	for rows.Next() {
		var i ListParticipantsForTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.UserID,
			&i.GuestName,
			&i.DeckID,
			&i.CommanderName,
			&i.Points,
			&i.CreatedAt,
			&i.Username,
			&i.DeckName,
			&i.DeckCommander,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPastSeatsForTournament = `-- name: ListPastSeatsForTournament :many
SELECT tts.tournament_table_id, tts.tournament_participant_id
FROM tournament_table_seats tts
JOIN tournament_tables tt ON tt.id = tts.tournament_table_id
JOIN tournament_rounds tr ON tr.id = tt.tournament_round_id
WHERE tr.tournament_id = $1
`

type ListPastSeatsForTournamentRow struct {
	TournamentTableID       pgtype.UUID `json:"tournament_table_id"`
	TournamentParticipantID pgtype.UUID `json:"tournament_participant_id"`
}

// Every (table_id, participant_id) pair across every round already played in this
// tournament, for pairing.go to compute who's already played whom.
func (q *Queries) ListPastSeatsForTournament(ctx context.Context, tournamentID pgtype.UUID) ([]ListPastSeatsForTournamentRow, error) {
	rows, err := q.db.Query(ctx, listPastSeatsForTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPastSeatsForTournamentRow
	for rows.Next() {
		var i ListPastSeatsForTournamentRow
		if err := rows.Scan(&i.TournamentTableID, &i.TournamentParticipantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatsForRound = `-- name: ListSeatsForRound :many
SELECT
  tt.id AS table_id, tt.table_number,
  tts.id AS seat_id, tts.tournament_participant_id, tts.finish_position, tts.points_awarded,
  tp.user_id, tp.guest_name, tp.commander_name AS participant_commander_name,
  u.username, d.name AS deck_name, d.commander AS deck_commander
FROM tournament_tables tt
JOIN tournament_table_seats tts ON tts.tournament_table_id = tt.id
JOIN tournament_participants tp ON tp.id = tts.tournament_participant_id
LEFT JOIN users u ON u.id = tp.user_id
LEFT JOIN decks d ON d.id = tp.deck_id
WHERE tt.tournament_round_id = $1
ORDER BY tt.table_number, tp.points DESC
`

type ListSeatsForRoundRow struct {
	TableID                  pgtype.UUID `json:"table_id"`
	TableNumber              int32       `json:"table_number"`
	SeatID                   pgtype.UUID `json:"seat_id"`
	TournamentParticipantID  pgtype.UUID `json:"tournament_participant_id"`
	FinishPosition           pgtype.Int4 `json:"finish_position"`
	PointsAwarded            int32       `json:"points_awarded"`
	UserID                   pgtype.UUID `json:"user_id"`
	GuestName                pgtype.Text `json:"guest_name"`
	ParticipantCommanderName pgtype.Text `json:"participant_commander_name"`
	Username                 pgtype.Text `json:"username"`
	DeckName                 pgtype.Text `json:"deck_name"`
	DeckCommander            pgtype.Text `json:"deck_commander"`
}

// Enriched fetch of every table+seat in a round (table number, seat/participant
// identity, and result if recorded) in one query, same batched-enrichment shape
// as statistics.ListPlayersForGames -- grouped by table_number in Go.
func (q *Queries) ListSeatsForRound(ctx context.Context, tournamentRoundID pgtype.UUID) ([]ListSeatsForRoundRow, error) {
	rows, err := q.db.Query(ctx, listSeatsForRound, tournamentRoundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeatsForRoundRow
	for rows.Next() {
		var i ListSeatsForRoundRow
		if err := rows.Scan(
			&i.TableID,
			&i.TableNumber,
			&i.SeatID,
			&i.TournamentParticipantID,
			&i.FinishPosition,
			&i.PointsAwarded,
			&i.UserID,
			&i.GuestName,
			&i.ParticipantCommanderName,
			&i.Username,
			&i.DeckName,
			&i.DeckCommander,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeatsForTable = `-- name: ListSeatsForTable :many
SELECT tts.id, tts.tournament_table_id, tts.tournament_participant_id, tts.finish_position, tts.points_awarded FROM tournament_table_seats tts WHERE tts.tournament_table_id = $1
`

func (q *Queries) ListSeatsForTable(ctx context.Context, tournamentTableID pgtype.UUID) ([]TournamentTableSeat, error) {
	rows, err := q.db.Query(ctx, listSeatsForTable, tournamentTableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TournamentTableSeat
	for rows.Next() {
		var i TournamentTableSeat
		if err := rows.Scan(
			&i.ID,
			&i.TournamentTableID,
			&i.TournamentParticipantID,
			&i.FinishPosition,
			&i.PointsAwarded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournamentsForUserPage = `-- name: ListTournamentsForUserPage :many
SELECT DISTINCT t.id, t.organizer_id, t.name, t.format, t.target_players, t.status, t.round_count, t.current_round, t.join_code, t.created_at, t.started_at, t.finished_at FROM tournaments t
LEFT JOIN tournament_participants tp
  ON tp.tournament_id = t.id AND tp.user_id = $1::uuid
WHERE (t.organizer_id = $1::uuid OR tp.id IS NOT NULL)
  AND (
    $2::timestamp IS NULL
    OR (t.created_at, t.id) < ($2::timestamp, $3::uuid)
  )
ORDER BY t.created_at DESC, t.id DESC
LIMIT $4
`

type ListTournamentsForUserPageParams struct {
	UserID          pgtype.UUID      `json:"user_id"`
	CursorCreatedAt pgtype.Timestamp `json:"cursor_created_at"`
	CursorID        pgtype.UUID      `json:"cursor_id"`
	PageLimit       int32            `json:"page_limit"`
}

// Tournaments the user organizes OR participates in, keyset-paginated over
// (created_at, id) DESC, same shape as playgroups.ListPlaygroupsForUserPage.
func (q *Queries) ListTournamentsForUserPage(ctx context.Context, arg ListTournamentsForUserPageParams) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, listTournamentsForUserPage,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tournament
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.OrganizerID,
			&i.Name,
			&i.Format,
			&i.TargetPlayers,
			&i.Status,
			&i.RoundCount,
			&i.CurrentRound,
			&i.JoinCode,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSeatResult = `-- name: RecordSeatResult :one
UPDATE tournament_table_seats
SET finish_position = $1, points_awarded = $2
WHERE id = $3
RETURNING id, tournament_table_id, tournament_participant_id, finish_position, points_awarded
`

type RecordSeatResultParams struct {
	FinishPosition pgtype.Int4 `json:"finish_position"`
	PointsAwarded  int32       `json:"points_awarded"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) RecordSeatResult(ctx context.Context, arg RecordSeatResultParams) (TournamentTableSeat, error) {
	row := q.db.QueryRow(ctx, recordSeatResult, arg.FinishPosition, arg.PointsAwarded, arg.ID)
	var i TournamentTableSeat
	err := row.Scan(
		&i.ID,
		&i.TournamentTableID,
		&i.TournamentParticipantID,
		&i.FinishPosition,
		&i.PointsAwarded,
	)
	return i, err
}

const startTournament = `-- name: StartTournament :one
UPDATE tournaments
SET status = 'in_progress', round_count = $1, current_round = 1, started_at = now()
WHERE id = $2
RETURNING id, organizer_id, name, format, target_players, status, round_count, current_round, join_code, created_at, started_at, finished_at
`

type StartTournamentParams struct {
	RoundCount pgtype.Int4 `json:"round_count"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) StartTournament(ctx context.Context, arg StartTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, startTournament, arg.RoundCount, arg.ID)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.OrganizerID,
		&i.Name,
		&i.Format,
		&i.TargetPlayers,
		&i.Status,
		&i.RoundCount,
		&i.CurrentRound,
		&i.JoinCode,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
