// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tournaments

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddParticipantPoints(ctx context.Context, arg AddParticipantPointsParams) (TournamentParticipant, error)
	AdvanceTournamentRound(ctx context.Context, id pgtype.UUID) (Tournament, error)
	CountParticipants(ctx context.Context, tournamentID pgtype.UUID) (int32, error)
	CountUnrecordedSeatsInRound(ctx context.Context, tournamentRoundID pgtype.UUID) (int32, error)
	CreateParticipant(ctx context.Context, arg CreateParticipantParams) (TournamentParticipant, error)
	CreateRound(ctx context.Context, arg CreateRoundParams) (TournamentRound, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (TournamentTable, error)
	CreateTableSeat(ctx context.Context, arg CreateTableSeatParams) (TournamentTableSeat, error)
	CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error)
	// Only needed to delete a tournament still in 'registration': rounds/tables/seats
	// don't exist yet at that point (StartTournament is what creates the first ones),
	// so participants are the only rows referencing it. See service.DeleteTournament.
	DeleteParticipantsForTournament(ctx context.Context, tournamentID pgtype.UUID) error
	DeleteTournament(ctx context.Context, id pgtype.UUID) error
	FinishRound(ctx context.Context, id pgtype.UUID) (TournamentRound, error)
	FinishTournament(ctx context.Context, id pgtype.UUID) (Tournament, error)
	GetParticipant(ctx context.Context, id pgtype.UUID) (TournamentParticipant, error)
	GetParticipantByUser(ctx context.Context, arg GetParticipantByUserParams) (GetParticipantByUserRow, error)
	GetRound(ctx context.Context, id pgtype.UUID) (TournamentRound, error)
	GetRoundByNumber(ctx context.Context, arg GetRoundByNumberParams) (TournamentRound, error)
	GetTable(ctx context.Context, id pgtype.UUID) (TournamentTable, error)
	GetTableForParticipantInRound(ctx context.Context, arg GetTableForParticipantInRoundParams) (TournamentTable, error)
	GetTournament(ctx context.Context, id pgtype.UUID) (Tournament, error)
	GetTournamentByJoinCode(ctx context.Context, joinCode string) (Tournament, error)
	// Same enrichment as ListSeatsForRound, scoped to a single table (used to
	// render the response right after RecordTableResult, without re-fetching the
	// whole round).
	ListEnrichedSeatsForTable(ctx context.Context, tournamentTableID pgtype.UUID) ([]ListEnrichedSeatsForTableRow, error)
	// Standings order: most points first, registration order breaks ties (see
	// pairing.go's doc for why no fancier tiebreaker is computed).
	ListParticipantsForTournament(ctx context.Context, tournamentID pgtype.UUID) ([]ListParticipantsForTournamentRow, error)
	// Every (table_id, participant_id) pair across every round already played in this
	// tournament, for pairing.go to compute who's already played whom.
	ListPastSeatsForTournament(ctx context.Context, tournamentID pgtype.UUID) ([]ListPastSeatsForTournamentRow, error)
	// Enriched fetch of every table+seat in a round (table number, seat/participant
	// identity, and result if recorded) in one query, same batched-enrichment shape
	// as statistics.ListPlayersForGames -- grouped by table_number in Go.
	ListSeatsForRound(ctx context.Context, tournamentRoundID pgtype.UUID) ([]ListSeatsForRoundRow, error)
	ListSeatsForTable(ctx context.Context, tournamentTableID pgtype.UUID) ([]TournamentTableSeat, error)
	// Tournaments the user organizes OR participates in, keyset-paginated over
	// (created_at, id) DESC, same shape as playgroups.ListPlaygroupsForUserPage.
	ListTournamentsForUserPage(ctx context.Context, arg ListTournamentsForUserPageParams) ([]Tournament, error)
	RecordSeatResult(ctx context.Context, arg RecordSeatResultParams) (TournamentTableSeat, error)
	StartTournament(ctx context.Context, arg StartTournamentParams) (Tournament, error)
}

var _ Querier = (*Queries)(nil)
