// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package statistics

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFinishedGamesForPlaygroup = `-- name: CountFinishedGamesForPlaygroup :one
SELECT COUNT(*) FROM games WHERE playgroup_id = $1 AND status = 'finished'
`

func (q *Queries) CountFinishedGamesForPlaygroup(ctx context.Context, playgroupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFinishedGamesForPlaygroup, playgroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDeckByID = `-- name: GetDeckByID :one
SELECT id, user_id, name, commander, moxfield_id, created_at, updated_at, image_url FROM decks WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDeckByID(ctx context.Context, id pgtype.UUID) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckByID, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Commander,
		&i.MoxfieldID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const getDeckStatistics = `-- name: GetDeckStatistics :one
SELECT deck_id, games_played, games_won, highest_life_total_achieved, total_commander_damage_dealt, last_recalculated_at FROM deck_statistics_summary
WHERE deck_id = $1 LIMIT 1
`

func (q *Queries) GetDeckStatistics(ctx context.Context, deckID pgtype.UUID) (DeckStatisticsSummary, error) {
	row := q.db.QueryRow(ctx, getDeckStatistics, deckID)
	var i DeckStatisticsSummary
	err := row.Scan(
		&i.DeckID,
		&i.GamesPlayed,
		&i.GamesWon,
		&i.HighestLifeTotalAchieved,
		&i.TotalCommanderDamageDealt,
		&i.LastRecalculatedAt,
	)
	return i, err
}

const getUserStatistics = `-- name: GetUserStatistics :one
SELECT user_id, games_played, games_won, total_damage_dealt, total_commander_damage_dealt, total_eliminations, last_recalculated_at FROM user_statistics_summary
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserStatistics(ctx context.Context, userID pgtype.UUID) (UserStatisticsSummary, error) {
	row := q.db.QueryRow(ctx, getUserStatistics, userID)
	var i UserStatisticsSummary
	err := row.Scan(
		&i.UserID,
		&i.GamesPlayed,
		&i.GamesWon,
		&i.TotalDamageDealt,
		&i.TotalCommanderDamageDealt,
		&i.TotalEliminations,
		&i.LastRecalculatedAt,
	)
	return i, err
}

const listDeckStatisticsForUser = `-- name: ListDeckStatisticsForUser :many
SELECT
  d.id AS deck_id,
  COALESCE(s.games_played, 0)::int AS games_played,
  COALESCE(s.games_won, 0)::int AS games_won,
  COALESCE(s.highest_life_total_achieved, 0)::int AS highest_life_total_achieved,
  COALESCE(s.total_commander_damage_dealt, 0)::int AS total_commander_damage_dealt
FROM decks d
LEFT JOIN deck_statistics_summary s ON s.deck_id = d.id
WHERE d.user_id = $1
ORDER BY d.created_at DESC
`

type ListDeckStatisticsForUserRow struct {
	DeckID                    pgtype.UUID `json:"deck_id"`
	GamesPlayed               int32       `json:"games_played"`
	GamesWon                  int32       `json:"games_won"`
	HighestLifeTotalAchieved  int32       `json:"highest_life_total_achieved"`
	TotalCommanderDamageDealt int32       `json:"total_commander_damage_dealt"`
}

// Every deck owned by the user, LEFT JOINed against its summary row (a deck
// never played has none) so a single query replaces the GetDeckStats N+1 the
// web dashboard used to do (one request per deck): see internal/decks for
// the ordering/definition of "owned by the user".
func (q *Queries) ListDeckStatisticsForUser(ctx context.Context, userID pgtype.UUID) ([]ListDeckStatisticsForUserRow, error) {
	rows, err := q.db.Query(ctx, listDeckStatisticsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeckStatisticsForUserRow
	for rows.Next() {
		var i ListDeckStatisticsForUserRow
		if err := rows.Scan(
			&i.DeckID,
			&i.GamesPlayed,
			&i.GamesWon,
			&i.HighestLifeTotalAchieved,
			&i.TotalCommanderDamageDealt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinishedGamesPage = `-- name: ListFinishedGamesPage :many
SELECT
  games.id, games.playgroup_id, games.started_at, games.finished_at, games.created_at,
  pg.name AS playgroup_name
FROM games
LEFT JOIN playgroups pg ON pg.id = games.playgroup_id
WHERE games.status = 'finished'
  AND EXISTS (
    SELECT 1 FROM game_players gp
    WHERE gp.game_id = games.id AND gp.user_id = $1::uuid
  )
  AND (
    $2::timestamp IS NULL
    OR (games.created_at, games.id) < ($2::timestamp, $3::uuid)
  )
ORDER BY games.created_at DESC, games.id DESC
LIMIT $4
`

type ListFinishedGamesPageParams struct {
	UserID          pgtype.UUID      `json:"user_id"`
	CursorCreatedAt pgtype.Timestamp `json:"cursor_created_at"`
	CursorID        pgtype.UUID      `json:"cursor_id"`
	PageLimit       int32            `json:"page_limit"`
}

type ListFinishedGamesPageRow struct {
	ID            pgtype.UUID      `json:"id"`
	PlaygroupID   pgtype.UUID      `json:"playgroup_id"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	FinishedAt    pgtype.Timestamp `json:"finished_at"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	PlaygroupName pgtype.Text      `json:"playgroup_name"`
}

// Keyset pagination over (created_at, id) DESC, scoped to finished games where
// the authenticated user had a seat -- same shape as games.ListGamesPage, but
// owned here because GET /statistics/games needs the denormalized
// player/deck/username data GET /games deliberately doesn't carry (that one is
// shared with the dashboard/join-game flow, kept lean on purpose).
func (q *Queries) ListFinishedGamesPage(ctx context.Context, arg ListFinishedGamesPageParams) ([]ListFinishedGamesPageRow, error) {
	rows, err := q.db.Query(ctx, listFinishedGamesPage,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFinishedGamesPageRow
	for rows.Next() {
		var i ListFinishedGamesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.PlaygroupID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.PlaygroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameActionSummaryForGames = `-- name: ListGameActionSummaryForGames :many
WITH turns AS (
  SELECT game_id, COUNT(*)::int AS turn_count
  FROM game_actions
  WHERE game_id = ANY($1::uuid[]) AND action_type = 'TurnStart'
  GROUP BY game_id
),
hits AS (
  SELECT DISTINCT ON (game_id)
    game_id,
    actor_id,
    (payload->>'amount')::int AS amount
  FROM game_actions
  WHERE game_id = ANY($1::uuid[])
    AND action_type IN ('CombatDamage', 'CommanderDamage')
  ORDER BY game_id, (payload->>'amount')::int DESC
)
SELECT
  ids.game_id::uuid AS game_id,
  COALESCE(t.turn_count, 0)::int AS turn_count,
  h.amount AS biggest_hit_amount,
  u.username AS biggest_hit_username
FROM unnest($1::uuid[]) AS ids(game_id)
LEFT JOIN turns t ON t.game_id = ids.game_id
LEFT JOIN hits h ON h.game_id = ids.game_id
LEFT JOIN game_players gp ON gp.id = h.actor_id
LEFT JOIN users u ON u.id = gp.user_id
`

type ListGameActionSummaryForGamesRow struct {
	GameID             pgtype.UUID `json:"game_id"`
	TurnCount          int32       `json:"turn_count"`
	BiggestHitAmount   pgtype.Int4 `json:"biggest_hit_amount"`
	BiggestHitUsername pgtype.Text `json:"biggest_hit_username"`
}

// For each game in game_ids: how many turns were played (every TurnStart belongs to
// one player's turn, so the count across the whole game is the turn count) and the
// single biggest hit (CombatDamage or CommanderDamage) dealt in it, with who dealt it --
// powers the finished-games card's "turns" and "biggest hit" stats without the client
// re-deriving them from the full action log. Left-joined from game_ids (not game_actions)
// so a game with no actions logged still gets a row (zero turns, no biggest hit).
func (q *Queries) ListGameActionSummaryForGames(ctx context.Context, gameIds []pgtype.UUID) ([]ListGameActionSummaryForGamesRow, error) {
	rows, err := q.db.Query(ctx, listGameActionSummaryForGames, gameIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGameActionSummaryForGamesRow
	for rows.Next() {
		var i ListGameActionSummaryForGamesRow
		if err := rows.Scan(
			&i.GameID,
			&i.TurnCount,
			&i.BiggestHitAmount,
			&i.BiggestHitUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameActionsForGame = `-- name: ListGameActionsForGame :many
SELECT id, game_id, actor_id, target_id, action_type, payload, created_at FROM game_actions WHERE game_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListGameActionsForGame(ctx context.Context, gameID pgtype.UUID) ([]GameAction, error) {
	rows, err := q.db.Query(ctx, listGameActionsForGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameAction
	for rows.Next() {
		var i GameAction
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.ActorID,
			&i.TargetID,
			&i.ActionType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamePlayersForGame = `-- name: ListGamePlayersForGame :many
SELECT id, game_id, user_id, deck_id, life_total, poison_counters, energy_counters, experience_counters, is_eliminated, added_by FROM game_players WHERE game_id = $1
`

func (q *Queries) ListGamePlayersForGame(ctx context.Context, gameID pgtype.UUID) ([]GamePlayer, error) {
	rows, err := q.db.Query(ctx, listGamePlayersForGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePlayer
	for rows.Next() {
		var i GamePlayer
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.DeckID,
			&i.LifeTotal,
			&i.PoisonCounters,
			&i.EnergyCounters,
			&i.ExperienceCounters,
			&i.IsEliminated,
			&i.AddedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpponentStats = `-- name: ListOpponentStats :many
SELECT
  other.user_id AS opponent_id,
  u.username AS opponent_username,
  COUNT(DISTINCT other.game_id)::int AS games_together,
  COUNT(DISTINCT you_eliminated.id)::int AS times_you_eliminated_them,
  COUNT(DISTINCT they_eliminated.id)::int AS times_eliminated_by_opponent
FROM game_players me
JOIN games g ON g.id = me.game_id AND g.status = 'finished'
JOIN game_players other ON other.game_id = me.game_id AND other.user_id != me.user_id
JOIN users u ON u.id = other.user_id
LEFT JOIN game_actions you_eliminated
  ON you_eliminated.game_id = me.game_id AND you_eliminated.action_type = 'Elimination'
  AND you_eliminated.actor_id = me.id AND you_eliminated.target_id = other.id
LEFT JOIN game_actions they_eliminated
  ON they_eliminated.game_id = me.game_id AND they_eliminated.action_type = 'Elimination'
  AND they_eliminated.actor_id = other.id AND they_eliminated.target_id = me.id
WHERE me.user_id = $1
GROUP BY other.user_id, u.username
`

type ListOpponentStatsRow struct {
	OpponentID                pgtype.UUID `json:"opponent_id"`
	OpponentUsername          string      `json:"opponent_username"`
	GamesTogether             int32       `json:"games_together"`
	TimesYouEliminatedThem    int32       `json:"times_you_eliminated_them"`
	TimesEliminatedByOpponent int32       `json:"times_eliminated_by_opponent"`
}

// Head-to-head aggregation across every finished game the user has played:
// for each other user they've shared a seat with, how many games together and
// how many times each side eliminated the other. Live-computed (no summary
// table), same choice as ListPlaygroupMemberGameStats above -- read once, on
// the statistics screen, not on every request like user_statistics_summary.
func (q *Queries) ListOpponentStats(ctx context.Context, userID pgtype.UUID) ([]ListOpponentStatsRow, error) {
	rows, err := q.db.Query(ctx, listOpponentStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpponentStatsRow
	for rows.Next() {
		var i ListOpponentStatsRow
		if err := rows.Scan(
			&i.OpponentID,
			&i.OpponentUsername,
			&i.GamesTogether,
			&i.TimesYouEliminatedThem,
			&i.TimesEliminatedByOpponent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayersForGames = `-- name: ListPlayersForGames :many
SELECT
  gp.game_id, gp.user_id, u.username, gp.deck_id, d.name AS deck_name,
  d.commander AS deck_commander, d.image_url AS deck_image_url,
  (winner.id IS NOT NULL)::boolean AS won
FROM game_players gp
JOIN users u ON u.id = gp.user_id
JOIN decks d ON d.id = gp.deck_id
LEFT JOIN (
  SELECT id, game_id
  FROM (
    SELECT id, game_id, COUNT(*) OVER (PARTITION BY game_id) AS alive_count
    FROM game_players
    WHERE NOT is_eliminated
  ) alive
  WHERE alive_count = 1
) winner ON winner.game_id = gp.game_id AND winner.id = gp.id
WHERE gp.game_id = ANY($1::uuid[])
`

type ListPlayersForGamesRow struct {
	GameID        pgtype.UUID `json:"game_id"`
	UserID        pgtype.UUID `json:"user_id"`
	Username      string      `json:"username"`
	DeckID        pgtype.UUID `json:"deck_id"`
	DeckName      string      `json:"deck_name"`
	DeckCommander string      `json:"deck_commander"`
	DeckImageUrl  pgtype.Text `json:"deck_image_url"`
	Won           bool        `json:"won"`
}

// Batched fetch of every seat across a page of games (see ListFinishedGamesPage),
// enriched with username, deck name/commander/image, and a `won` flag -- one
// round trip for the whole page instead of one per game. The winner subquery
// (only non-eliminated seat, if there's exactly one) mirrors the identical
// pattern already used in ListPlaygroupMemberGameStats above -- same rule,
// same SQL shape, not reinvented.
func (q *Queries) ListPlayersForGames(ctx context.Context, gameIds []pgtype.UUID) ([]ListPlayersForGamesRow, error) {
	rows, err := q.db.Query(ctx, listPlayersForGames, gameIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersForGamesRow
	for rows.Next() {
		var i ListPlayersForGamesRow
		if err := rows.Scan(
			&i.GameID,
			&i.UserID,
			&i.Username,
			&i.DeckID,
			&i.DeckName,
			&i.DeckCommander,
			&i.DeckImageUrl,
			&i.Won,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaygroupGameCountsForUser = `-- name: ListPlaygroupGameCountsForUser :many
SELECT
  pg.id AS playgroup_id,
  pg.name AS playgroup_name,
  COUNT(DISTINCT gp.game_id)::int AS games_played
FROM playgroup_members pm
JOIN playgroups pg ON pg.id = pm.playgroup_id
LEFT JOIN game_players gp
  ON gp.user_id = pm.user_id
  AND EXISTS (
    SELECT 1 FROM games g
    WHERE g.id = gp.game_id AND g.playgroup_id = pg.id AND g.status = 'finished'
  )
WHERE pm.user_id = $1
GROUP BY pg.id, pg.name
`

type ListPlaygroupGameCountsForUserRow struct {
	PlaygroupID   pgtype.UUID `json:"playgroup_id"`
	PlaygroupName string      `json:"playgroup_name"`
	GamesPlayed   int32       `json:"games_played"`
}

// Every playgroup the user belongs to, with how many finished games they've
// played within it -- single query replacing the per-group GetPlaygroupStats
// loop the statistics screens used to do (same "every owned/joined X" shape
// as ListDeckStatisticsForUser above).
func (q *Queries) ListPlaygroupGameCountsForUser(ctx context.Context, userID pgtype.UUID) ([]ListPlaygroupGameCountsForUserRow, error) {
	rows, err := q.db.Query(ctx, listPlaygroupGameCountsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaygroupGameCountsForUserRow
	for rows.Next() {
		var i ListPlaygroupGameCountsForUserRow
		if err := rows.Scan(&i.PlaygroupID, &i.PlaygroupName, &i.GamesPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaygroupMemberGameStats = `-- name: ListPlaygroupMemberGameStats :many
SELECT
  gp.user_id,
  COUNT(DISTINCT gp.game_id)::int AS games_played,
  COUNT(DISTINCT winner.id)::int AS games_won
FROM game_players gp
JOIN games g ON g.id = gp.game_id
LEFT JOIN (
  -- The winner of a game is the only player still alive at the end; the
  -- alive_count = 1 filter selects that row without needing MIN()/MAX()
  -- over uuid (Postgres has no ordering operator for that type).
  SELECT id, game_id
  FROM (
    SELECT id, game_id, COUNT(*) OVER (PARTITION BY game_id) AS alive_count
    FROM game_players
    WHERE NOT is_eliminated
  ) alive
  WHERE alive_count = 1
) winner ON winner.game_id = gp.game_id AND winner.id = gp.id
WHERE g.playgroup_id = $1 AND g.status = 'finished'
GROUP BY gp.user_id
`

type ListPlaygroupMemberGameStatsRow struct {
	UserID      pgtype.UUID `json:"user_id"`
	GamesPlayed int32       `json:"games_played"`
	GamesWon    int32       `json:"games_won"`
}

func (q *Queries) ListPlaygroupMemberGameStats(ctx context.Context, playgroupID pgtype.UUID) ([]ListPlaygroupMemberGameStatsRow, error) {
	rows, err := q.db.Query(ctx, listPlaygroupMemberGameStats, playgroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaygroupMemberGameStatsRow
	for rows.Next() {
		var i ListPlaygroupMemberGameStatsRow
		if err := rows.Scan(&i.UserID, &i.GamesPlayed, &i.GamesWon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeckStatistics = `-- name: UpsertDeckStatistics :exec
INSERT INTO deck_statistics_summary (
  deck_id, games_played, games_won, highest_life_total_achieved, total_commander_damage_dealt
)
VALUES ($1, $2, $3, $4,
        $5)
ON CONFLICT (deck_id) DO UPDATE SET
  games_played = deck_statistics_summary.games_played + EXCLUDED.games_played,
  games_won = deck_statistics_summary.games_won + EXCLUDED.games_won,
  highest_life_total_achieved = GREATEST(deck_statistics_summary.highest_life_total_achieved, EXCLUDED.highest_life_total_achieved),
  total_commander_damage_dealt = deck_statistics_summary.total_commander_damage_dealt + EXCLUDED.total_commander_damage_dealt,
  last_recalculated_at = now()
`

type UpsertDeckStatisticsParams struct {
	DeckID                    pgtype.UUID `json:"deck_id"`
	GamesPlayed               pgtype.Int4 `json:"games_played"`
	GamesWon                  pgtype.Int4 `json:"games_won"`
	HighestLifeTotalAchieved  pgtype.Int4 `json:"highest_life_total_achieved"`
	TotalCommanderDamageDealt pgtype.Int4 `json:"total_commander_damage_dealt"`
}

func (q *Queries) UpsertDeckStatistics(ctx context.Context, arg UpsertDeckStatisticsParams) error {
	_, err := q.db.Exec(ctx, upsertDeckStatistics,
		arg.DeckID,
		arg.GamesPlayed,
		arg.GamesWon,
		arg.HighestLifeTotalAchieved,
		arg.TotalCommanderDamageDealt,
	)
	return err
}

const upsertUserStatistics = `-- name: UpsertUserStatistics :exec
INSERT INTO user_statistics_summary (
  user_id, games_played, games_won, total_damage_dealt, total_commander_damage_dealt, total_eliminations
)
VALUES ($1, $2, $3, $4,
        $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
  games_played = user_statistics_summary.games_played + EXCLUDED.games_played,
  games_won = user_statistics_summary.games_won + EXCLUDED.games_won,
  total_damage_dealt = user_statistics_summary.total_damage_dealt + EXCLUDED.total_damage_dealt,
  total_commander_damage_dealt = user_statistics_summary.total_commander_damage_dealt + EXCLUDED.total_commander_damage_dealt,
  total_eliminations = user_statistics_summary.total_eliminations + EXCLUDED.total_eliminations,
  last_recalculated_at = now()
`

type UpsertUserStatisticsParams struct {
	UserID                    pgtype.UUID `json:"user_id"`
	GamesPlayed               pgtype.Int4 `json:"games_played"`
	GamesWon                  pgtype.Int4 `json:"games_won"`
	TotalDamageDealt          pgtype.Int4 `json:"total_damage_dealt"`
	TotalCommanderDamageDealt pgtype.Int4 `json:"total_commander_damage_dealt"`
	TotalEliminations         pgtype.Int4 `json:"total_eliminations"`
}

func (q *Queries) UpsertUserStatistics(ctx context.Context, arg UpsertUserStatisticsParams) error {
	_, err := q.db.Exec(ctx, upsertUserStatistics,
		arg.UserID,
		arg.GamesPlayed,
		arg.GamesWon,
		arg.TotalDamageDealt,
		arg.TotalCommanderDamageDealt,
		arg.TotalEliminations,
	)
	return err
}
