// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package statistics

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetDeckStatistics(ctx context.Context, deckID pgtype.UUID) (DeckStatisticsSummary, error)
	GetUserStatistics(ctx context.Context, userID pgtype.UUID) (UserStatisticsSummary, error)
}

var _ Querier = (*Queries)(nil)
