// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package statistics

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeckStatistics = `-- name: GetDeckStatistics :one
SELECT deck_id, games_played, games_won, highest_life_total_achieved, total_commander_damage_dealt, last_recalculated_at FROM deck_statistics_summary
WHERE deck_id = $1 LIMIT 1
`

func (q *Queries) GetDeckStatistics(ctx context.Context, deckID pgtype.UUID) (DeckStatisticsSummary, error) {
	row := q.db.QueryRow(ctx, getDeckStatistics, deckID)
	var i DeckStatisticsSummary
	err := row.Scan(
		&i.DeckID,
		&i.GamesPlayed,
		&i.GamesWon,
		&i.HighestLifeTotalAchieved,
		&i.TotalCommanderDamageDealt,
		&i.LastRecalculatedAt,
	)
	return i, err
}

const getUserStatistics = `-- name: GetUserStatistics :one
SELECT user_id, games_played, games_won, total_damage_dealt, total_commander_damage_dealt, total_eliminations, last_recalculated_at FROM user_statistics_summary
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserStatistics(ctx context.Context, userID pgtype.UUID) (UserStatisticsSummary, error) {
	row := q.db.QueryRow(ctx, getUserStatistics, userID)
	var i UserStatisticsSummary
	err := row.Scan(
		&i.UserID,
		&i.GamesPlayed,
		&i.GamesWon,
		&i.TotalDamageDealt,
		&i.TotalCommanderDamageDealt,
		&i.TotalEliminations,
		&i.LastRecalculatedAt,
	)
	return i, err
}
