// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package statistics

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountDecksForUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountFinishedGamesForPlaygroup(ctx context.Context, playgroupID pgtype.UUID) (int64, error)
	CountPlaygroupsForUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	// How many finished games in a row, counting back from the most recent, ended
	// the same way for this user. Computed in SQL and returned as a single row: the
	// naive version ships every game the user ever played to the client just to
	// count a handful of them off the top.
	//
	// `won` uses the same sole-survivor rule as ListPlaygroupMemberGameStats and
	// ListPlayersForGames, so the streak agrees with the win rate shown next to it.
	GetCurrentStreakForUser(ctx context.Context, userID pgtype.UUID) (GetCurrentStreakForUserRow, error)
	// The spotlight card: highest win rate among the user's decks that have
	// actually been played. games_played > 0 both defines "has a win rate" and
	// keeps the division safe. Ties break towards the deck with more games -- a
	// single lucky win shouldn't outrank a long winning record.
	GetDashboardBestDeckForUser(ctx context.Context, userID pgtype.UUID) (GetDashboardBestDeckForUserRow, error)
	GetDeckByID(ctx context.Context, id pgtype.UUID) (Deck, error)
	GetDeckStatistics(ctx context.Context, deckID pgtype.UUID) (DeckStatisticsSummary, error)
	GetUserStatistics(ctx context.Context, userID pgtype.UUID) (UserStatisticsSummary, error)
	// The decks the dashboard's "your decks" strip shows: most played first, capped
	// at the handful that fit. Same decks LEFT JOIN summary shape as
	// ListDeckStatisticsForUser (a deck never played has no summary row), but
	// ordered and limited here instead of returning the whole collection for the
	// client to sort and slice.
	ListDashboardDecksForUser(ctx context.Context, arg ListDashboardDecksForUserParams) ([]ListDashboardDecksForUserRow, error)
	// Members of the groups the dashboard is about to render, batched in one round
	// trip (same game_id = ANY(...) shape as ListPlayersForGames below). Only feeds
	// the avatar strip, so the service keeps the first few per group.
	ListDashboardPlaygroupMembers(ctx context.Context, playgroupIds []pgtype.UUID) ([]ListDashboardPlaygroupMembersRow, error)
	// The group cards, in the same order GET /playgroups uses (newest first), so
	// the dashboard shows the same first groups the playgroups screen does.
	// games_played counts the group's finished games, not the caller's -- that's
	// what the card says ("N games played" for the group).
	ListDashboardPlaygroupsForUser(ctx context.Context, arg ListDashboardPlaygroupsForUserParams) ([]ListDashboardPlaygroupsForUserRow, error)
	// Every deck owned by the user, LEFT JOINed against its summary row (a deck
	// never played has none) so a single query replaces the GetDeckStats N+1 the
	// web dashboard used to do (one request per deck): see internal/decks for
	// the ordering/definition of "owned by the user".
	ListDeckStatisticsForUser(ctx context.Context, userID pgtype.UUID) ([]ListDeckStatisticsForUserRow, error)
	// Keyset pagination over (created_at, id) DESC, scoped to finished games where
	// the authenticated user had a seat -- same shape as games.ListGamesPage, but
	// owned here because GET /statistics/games needs the denormalized
	// player/deck/username data GET /games deliberately doesn't carry (that one is
	// shared with the dashboard/join-game flow, kept lean on purpose).
	ListFinishedGamesPage(ctx context.Context, arg ListFinishedGamesPageParams) ([]ListFinishedGamesPageRow, error)
	// For each game in game_ids: how many turns were played (every TurnStart belongs to
	// one player's turn, so the count across the whole game is the turn count) and the
	// single biggest hit (CombatDamage or CommanderDamage) dealt in it, with who dealt it --
	// powers the finished-games card's "turns" and "biggest hit" stats without the client
	// re-deriving them from the full action log. Left-joined from game_ids (not game_actions)
	// so a game with no actions logged still gets a row (zero turns, no biggest hit).
	ListGameActionSummaryForGames(ctx context.Context, gameIds []pgtype.UUID) ([]ListGameActionSummaryForGamesRow, error)
	ListGameActionsForGame(ctx context.Context, gameID pgtype.UUID) ([]GameAction, error)
	ListGamePlayersForGame(ctx context.Context, gameID pgtype.UUID) ([]GamePlayer, error)
	// Head-to-head aggregation across every finished game the user has played:
	// for each other user they've shared a seat with, how many games together and
	// how many times each side eliminated the other. Live-computed (no summary
	// table), same choice as ListPlaygroupMemberGameStats above -- read once, on
	// the statistics screen, not on every request like user_statistics_summary.
	ListOpponentStats(ctx context.Context, userID pgtype.UUID) ([]ListOpponentStatsRow, error)
	// Batched fetch of every seat across a page of games (see ListFinishedGamesPage),
	// enriched with username, deck name/commander/image, and a `won` flag -- one
	// round trip for the whole page instead of one per game. The winner subquery
	// (only non-eliminated seat, if there's exactly one) mirrors the identical
	// pattern already used in ListPlaygroupMemberGameStats above -- same rule,
	// same SQL shape, not reinvented.
	ListPlayersForGames(ctx context.Context, gameIds []pgtype.UUID) ([]ListPlayersForGamesRow, error)
	// Every playgroup the user belongs to, with how many finished games they've
	// played within it -- single query replacing the per-group GetPlaygroupStats
	// loop the statistics screens used to do (same "every owned/joined X" shape
	// as ListDeckStatisticsForUser above).
	ListPlaygroupGameCountsForUser(ctx context.Context, userID pgtype.UUID) ([]ListPlaygroupGameCountsForUserRow, error)
	ListPlaygroupMemberGameStats(ctx context.Context, playgroupID pgtype.UUID) ([]ListPlaygroupMemberGameStatsRow, error)
	UpsertDeckStatistics(ctx context.Context, arg UpsertDeckStatisticsParams) error
	UpsertUserStatistics(ctx context.Context, arg UpsertUserStatisticsParams) error
}

var _ Querier = (*Queries)(nil)
