// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package friends

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (FriendRequest, error)
	// Removes an accepted friendship between user_a and user_b, regardless of direction.
	DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error
	// Whether user_a and user_b are already friends, regardless of who originally sent the request.
	GetAcceptedFriendship(ctx context.Context, arg GetAcceptedFriendshipParams) (FriendRequest, error)
	GetFriendRequestByID(ctx context.Context, id pgtype.UUID) (FriendRequest, error)
	// The pending request from requester_id to addressee_id, if any (same direction).
	GetPendingRequestBetween(ctx context.Context, arg GetPendingRequestBetweenParams) (FriendRequest, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// Accepted friendships of user_id, resolved to the OTHER user in the row
	// regardless of who originally sent the request.
	ListFriends(ctx context.Context, userID pgtype.UUID) ([]ListFriendsRow, error)
	// Pending requests addressed to user_id, with the requester's username.
	ListIncomingFriendRequests(ctx context.Context, addresseeID pgtype.UUID) ([]ListIncomingFriendRequestsRow, error)
	// Pending requests sent by user_id, with the addressee's username.
	ListOutgoingFriendRequests(ctx context.Context, requesterID pgtype.UUID) ([]ListOutgoingFriendRequestsRow, error)
	// Sets status to 'accepted'/'rejected'/'cancelled' and stamps responded_at. The
	// caller (service) is responsible for only passing one of those three values.
	RespondFriendRequest(ctx context.Context, arg RespondFriendRequestParams) (FriendRequest, error)
}

var _ Querier = (*Queries)(nil)
