// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package friends

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFriendRequest = `-- name: CreateFriendRequest :one
INSERT INTO friend_requests (requester_id, addressee_id)
VALUES ($1, $2)
RETURNING id, requester_id, addressee_id, status, created_at, responded_at
`

type CreateFriendRequestParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, createFriendRequest, arg.RequesterID, arg.AddresseeID)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friend_requests
WHERE status = 'accepted'
  AND ((requester_id = $1 AND addressee_id = $2)
    OR (requester_id = $2 AND addressee_id = $1))
`

type DeleteFriendshipParams struct {
	UserA pgtype.UUID `json:"user_a"`
	UserB pgtype.UUID `json:"user_b"`
}

// Removes an accepted friendship between user_a and user_b, regardless of direction.
func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.Exec(ctx, deleteFriendship, arg.UserA, arg.UserB)
	return err
}

const getAcceptedFriendship = `-- name: GetAcceptedFriendship :one
SELECT id, requester_id, addressee_id, status, created_at, responded_at FROM friend_requests
WHERE status = 'accepted'
  AND ((requester_id = $1 AND addressee_id = $2)
    OR (requester_id = $2 AND addressee_id = $1))
LIMIT 1
`

type GetAcceptedFriendshipParams struct {
	UserA pgtype.UUID `json:"user_a"`
	UserB pgtype.UUID `json:"user_b"`
}

// Whether user_a and user_b are already friends, regardless of who originally sent the request.
func (q *Queries) GetAcceptedFriendship(ctx context.Context, arg GetAcceptedFriendshipParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, getAcceptedFriendship, arg.UserA, arg.UserB)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getFriendRequestByID = `-- name: GetFriendRequestByID :one
SELECT id, requester_id, addressee_id, status, created_at, responded_at FROM friend_requests WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFriendRequestByID(ctx context.Context, id pgtype.UUID) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, getFriendRequestByID, id)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getPendingRequestBetween = `-- name: GetPendingRequestBetween :one
SELECT id, requester_id, addressee_id, status, created_at, responded_at FROM friend_requests
WHERE requester_id = $1 AND addressee_id = $2 AND status = 'pending'
LIMIT 1
`

type GetPendingRequestBetweenParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
}

// The pending request from requester_id to addressee_id, if any (same direction).
func (q *Queries) GetPendingRequestBetween(ctx context.Context, arg GetPendingRequestBetweenParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, getPendingRequestBetween, arg.RequesterID, arg.AddresseeID)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified, is_admin, is_active FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.IsActive,
	)
	return i, err
}

const listFriends = `-- name: ListFriends :many
SELECT
  fr.id,
  (CASE WHEN fr.requester_id = $1 THEN fr.addressee_id ELSE fr.requester_id END)::uuid AS friend_id,
  (CASE WHEN fr.requester_id = $1 THEN au.username ELSE ru.username END)::varchar AS friend_username,
  fr.responded_at AS friends_since
FROM friend_requests fr
JOIN users ru ON ru.id = fr.requester_id
JOIN users au ON au.id = fr.addressee_id
WHERE fr.status = 'accepted'
  AND (fr.requester_id = $1 OR fr.addressee_id = $1)
ORDER BY fr.created_at DESC
`

type ListFriendsRow struct {
	ID             pgtype.UUID      `json:"id"`
	FriendID       pgtype.UUID      `json:"friend_id"`
	FriendUsername string           `json:"friend_username"`
	FriendsSince   pgtype.Timestamp `json:"friends_since"`
}

// Accepted friendships of user_id, resolved to the OTHER user in the row
// regardless of who originally sent the request.
func (q *Queries) ListFriends(ctx context.Context, userID pgtype.UUID) ([]ListFriendsRow, error) {
	rows, err := q.db.Query(ctx, listFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsRow
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.FriendID,
			&i.FriendUsername,
			&i.FriendsSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingFriendRequests = `-- name: ListIncomingFriendRequests :many
SELECT fr.id, fr.requester_id, fr.addressee_id, fr.status, fr.created_at, fr.responded_at,
       u.username AS requester_username
FROM friend_requests fr
JOIN users u ON u.id = fr.requester_id
WHERE fr.addressee_id = $1 AND fr.status = 'pending'
ORDER BY fr.created_at DESC
`

type ListIncomingFriendRequestsRow struct {
	ID                pgtype.UUID      `json:"id"`
	RequesterID       pgtype.UUID      `json:"requester_id"`
	AddresseeID       pgtype.UUID      `json:"addressee_id"`
	Status            string           `json:"status"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	RespondedAt       pgtype.Timestamp `json:"responded_at"`
	RequesterUsername string           `json:"requester_username"`
}

// Pending requests addressed to user_id, with the requester's username.
func (q *Queries) ListIncomingFriendRequests(ctx context.Context, addresseeID pgtype.UUID) ([]ListIncomingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listIncomingFriendRequests, addresseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomingFriendRequestsRow
	for rows.Next() {
		var i ListIncomingFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.AddresseeID,
			&i.Status,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.RequesterUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingFriendRequests = `-- name: ListOutgoingFriendRequests :many
SELECT fr.id, fr.requester_id, fr.addressee_id, fr.status, fr.created_at, fr.responded_at,
       u.username AS addressee_username
FROM friend_requests fr
JOIN users u ON u.id = fr.addressee_id
WHERE fr.requester_id = $1 AND fr.status = 'pending'
ORDER BY fr.created_at DESC
`

type ListOutgoingFriendRequestsRow struct {
	ID                pgtype.UUID      `json:"id"`
	RequesterID       pgtype.UUID      `json:"requester_id"`
	AddresseeID       pgtype.UUID      `json:"addressee_id"`
	Status            string           `json:"status"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	RespondedAt       pgtype.Timestamp `json:"responded_at"`
	AddresseeUsername string           `json:"addressee_username"`
}

// Pending requests sent by user_id, with the addressee's username.
func (q *Queries) ListOutgoingFriendRequests(ctx context.Context, requesterID pgtype.UUID) ([]ListOutgoingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOutgoingFriendRequests, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutgoingFriendRequestsRow
	for rows.Next() {
		var i ListOutgoingFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.AddresseeID,
			&i.Status,
			&i.CreatedAt,
			&i.RespondedAt,
			&i.AddresseeUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const respondFriendRequest = `-- name: RespondFriendRequest :one
UPDATE friend_requests
SET status = $1, responded_at = now()
WHERE id = $2
RETURNING id, requester_id, addressee_id, status, created_at, responded_at
`

type RespondFriendRequestParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

// Sets status to 'accepted'/'rejected'/'cancelled' and stamps responded_at. The
// caller (service) is responsible for only passing one of those three values.
func (q *Queries) RespondFriendRequest(ctx context.Context, arg RespondFriendRequestParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, respondFriendRequest, arg.Status, arg.ID)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}
