// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package auth

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	RevokeAllRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error
}

var _ Querier = (*Queries)(nil)
