// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package users

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error)
	// email_verified is explicit (not the column default): RegisterUser decides its
	// value based on config.RequireEmailVerification (see ADR-0012). CreateUserWithGoogle
	// deliberately doesn't touch it, so it uses the column default (true) — Google already
	// confirms the email in its id_token.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserWithGoogle(ctx context.Context, arg CreateUserWithGoogleParams) (User, error)
	GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// email_verified is forced to true when linking: FindOrCreateGoogleUser already checked
	// that Google confirms this email before calling this query, so an email/password
	// account that isn't verified yet also gets verified through this path.
	LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) (User, error)
	MarkEmailVerificationTokenUsed(ctx context.Context, id pgtype.UUID) error
	// Partial, case-insensitive username search, to invite people to a playgroup without
	// knowing their UUID (see internal/playgroups). Deliberately does NOT search by email
	// this way (partial): it would allow enumerating other people's email addresses by
	// prefix/substring. Exact email search is handled separately, via GetUserByEmail.
	SearchUsersByUsername(ctx context.Context, arg SearchUsersByUsernameParams) ([]User, error)
	SetUserEmailVerified(ctx context.Context, id pgtype.UUID) (User, error)
	UpdateMoxfieldUsername(ctx context.Context, arg UpdateMoxfieldUsernameParams) (User, error)
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) (User, error)
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error)
	UsernameExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
