// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package users

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (
  user_id, token_hash, expires_at
) VALUES (
  $1, $2, $3
)
RETURNING id, user_id, token_hash, expires_at, created_at, used_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    pgtype.UUID      `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, email, password_hash, email_verified
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified
`

type CreateUserParams struct {
	Username      string      `json:"username"`
	Email         string      `json:"email"`
	PasswordHash  pgtype.Text `json:"password_hash"`
	EmailVerified bool        `json:"email_verified"`
}

// email_verified is explicit (not the column default): RegisterUser decides its
// value based on config.RequireEmailVerification (see ADR-0012). CreateUserWithGoogle
// deliberately doesn't touch it, so it uses the column default (true) — Google already
// confirms the email in its id_token.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
	)
	return i, err
}

const createUserWithGoogle = `-- name: CreateUserWithGoogle :one
INSERT INTO users (
  username, email, google_id
) VALUES (
  $1, $2, $3
)
RETURNING id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified
`

type CreateUserWithGoogleParams struct {
	Username string      `json:"username"`
	Email    string      `json:"email"`
	GoogleID pgtype.Text `json:"google_id"`
}

func (q *Queries) CreateUserWithGoogle(ctx context.Context, arg CreateUserWithGoogleParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithGoogle, arg.Username, arg.Email, arg.GoogleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
	)
	return i, err
}

const getEmailVerificationTokenByHash = `-- name: GetEmailVerificationTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at, used_at FROM email_verification_tokens
WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByHash, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified FROM users
WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
	)
	return i, err
}

const linkGoogleID = `-- name: LinkGoogleID :one
UPDATE users SET google_id = $2, email_verified = true
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified
`

type LinkGoogleIDParams struct {
	ID       pgtype.UUID `json:"id"`
	GoogleID pgtype.Text `json:"google_id"`
}

// email_verified is forced to true when linking: FindOrCreateGoogleUser already checked
// that Google confirms this email before calling this query, so an email/password
// account that isn't verified yet also gets verified through this path.
func (q *Queries) LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) (User, error) {
	row := q.db.QueryRow(ctx, linkGoogleID, arg.ID, arg.GoogleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
	)
	return i, err
}

const markEmailVerificationTokenUsed = `-- name: MarkEmailVerificationTokenUsed :exec
UPDATE email_verification_tokens SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkEmailVerificationTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerificationTokenUsed, id)
	return err
}

const searchUsersByUsername = `-- name: SearchUsersByUsername :many
SELECT id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified FROM users
WHERE username ILIKE '%' || $1 || '%'
ORDER BY username
LIMIT $2
`

type SearchUsersByUsernameParams struct {
	Pattern     pgtype.Text `json:"pattern"`
	ResultLimit int32       `json:"result_limit"`
}

// Partial, case-insensitive username search, to invite people to a playgroup without
// knowing their UUID (see internal/playgroups). Deliberately does NOT search by email
// this way (partial): it would allow enumerating other people's email addresses by
// prefix/substring. Exact email search is handled separately, via GetUserByEmail.
func (q *Queries) SearchUsersByUsername(ctx context.Context, arg SearchUsersByUsernameParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsersByUsername, arg.Pattern, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GoogleID,
			&i.MoxfieldUsername,
			&i.EmailVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :one
UPDATE users SET email_verified = true
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified
`

func (q *Queries) SetUserEmailVerified(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, setUserEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
	)
	return i, err
}

const updateMoxfieldUsername = `-- name: UpdateMoxfieldUsername :one
UPDATE users SET moxfield_username = $2
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified
`

type UpdateMoxfieldUsernameParams struct {
	ID               pgtype.UUID `json:"id"`
	MoxfieldUsername pgtype.Text `json:"moxfield_username"`
}

func (q *Queries) UpdateMoxfieldUsername(ctx context.Context, arg UpdateMoxfieldUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateMoxfieldUsername, arg.ID, arg.MoxfieldUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
	)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :one
UPDATE users SET password_hash = $2
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified
`

type UpdatePasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
	)
	return i, err
}

const updateUsername = `-- name: UpdateUsername :one
UPDATE users SET username = $2
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified
`

type UpdateUsernameParams struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
	)
	return i, err
}
