// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package users

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	// email_verified is explicit (not the column default): RegisterUser decides its
	// value based on config.RequireEmailVerification (see ADR-0012). CreateUserWithGoogle
	// deliberately doesn't touch it, so it uses the column default (true) — Google already
	// confirms the email in its id_token.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserWithGoogle(ctx context.Context, arg CreateUserWithGoogleParams) (User, error)
	GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error)
	// Case-insensitive on both sides: new rows are stored lowercased (see
	// normalizeEmail), but rows written before migration 00019 may not be. Served by
	// the users_email_lower_key index.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// Used by auth.RequireAdmin: is_admin is checked fresh from the DB on every
	// admin request rather than trusted from a JWT claim, see ADR-0018.
	GetUserRoleFlags(ctx context.Context, id pgtype.UUID) (GetUserRoleFlagsRow, error)
	// email_verified is forced to true when linking: FindOrCreateGoogleUser already checked
	// that Google confirms this email before calling this query, so an email/password
	// account that isn't verified yet also gets verified through this path.
	LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) (User, error)
	// FOR UPDATE: ResetPassword runs inside a transaction, so two requests racing with
	// the same link can't both see it unused and both change the password.
	LockPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	MarkEmailVerificationTokenUsed(ctx context.Context, id pgtype.UUID) error
	// Burns every outstanding reset link of the user, not just the one being redeemed: once
	// the password has changed, an older email sitting in the inbox must stop working too.
	MarkPasswordResetTokensUsedForUser(ctx context.Context, userID pgtype.UUID) error
	// email_verified is forced to true: redeeming a link sent to that address proves the
	// user owns it, same reasoning as LinkGoogleID.
	ResetPasswordHash(ctx context.Context, arg ResetPasswordHashParams) (User, error)
	// Same statement as auth's RevokeAllRefreshTokensForUser: a password reset signs the
	// account out everywhere, in case whoever had the old password still holds a session.
	RevokeUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	// Partial, case-insensitive username search, to invite people to a playgroup without
	// knowing their UUID (see internal/playgroups). Deliberately does NOT search by email
	// this way (partial): it would allow enumerating other people's email addresses by
	// prefix/substring. Exact email search is handled separately, via GetUserByEmail.
	SearchUsersByUsername(ctx context.Context, arg SearchUsersByUsernameParams) ([]User, error)
	SetUserEmailVerified(ctx context.Context, id pgtype.UUID) (User, error)
	// Records that the user just made an authenticated request (see ActivityTracker,
	// which throttles this to once per minute per user, and the admin overview's
	// online_users, which reads it).
	TouchLastSeen(ctx context.Context, id pgtype.UUID) error
	UpdateMoxfieldUsername(ctx context.Context, arg UpdateMoxfieldUsernameParams) (User, error)
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) (User, error)
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error)
	UsernameExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
