// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package users

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, email, password_hash
) VALUES (
  $1, $2, $3
)
RETURNING id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
	)
	return i, err
}

const createUserWithGoogle = `-- name: CreateUserWithGoogle :one
INSERT INTO users (
  username, email, google_id
) VALUES (
  $1, $2, $3
)
RETURNING id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username
`

type CreateUserWithGoogleParams struct {
	Username string      `json:"username"`
	Email    string      `json:"email"`
	GoogleID pgtype.Text `json:"google_id"`
}

func (q *Queries) CreateUserWithGoogle(ctx context.Context, arg CreateUserWithGoogleParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithGoogle, arg.Username, arg.Email, arg.GoogleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username FROM users
WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
	)
	return i, err
}

const linkGoogleID = `-- name: LinkGoogleID :one
UPDATE users SET google_id = $2
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username
`

type LinkGoogleIDParams struct {
	ID       pgtype.UUID `json:"id"`
	GoogleID pgtype.Text `json:"google_id"`
}

func (q *Queries) LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) (User, error) {
	row := q.db.QueryRow(ctx, linkGoogleID, arg.ID, arg.GoogleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
	)
	return i, err
}

const updateMoxfieldUsername = `-- name: UpdateMoxfieldUsername :one
UPDATE users SET moxfield_username = $2
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username
`

type UpdateMoxfieldUsernameParams struct {
	ID               pgtype.UUID `json:"id"`
	MoxfieldUsername pgtype.Text `json:"moxfield_username"`
}

func (q *Queries) UpdateMoxfieldUsername(ctx context.Context, arg UpdateMoxfieldUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateMoxfieldUsername, arg.ID, arg.MoxfieldUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
	)
	return i, err
}
