// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package deckresync

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResyncJob = `-- name: CreateResyncJob :one
INSERT INTO deck_resync_jobs (user_id, total_decks, status)
VALUES ($1, $2, 'in_progress')
RETURNING id, user_id, status, total_decks, updated_count, failed_count, error_message, created_at, updated_at, finished_at
`

type CreateResyncJobParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	TotalDecks int32       `json:"total_decks"`
}

func (q *Queries) CreateResyncJob(ctx context.Context, arg CreateResyncJobParams) (DeckResyncJob, error) {
	row := q.db.QueryRow(ctx, createResyncJob, arg.UserID, arg.TotalDecks)
	var i DeckResyncJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalDecks,
		&i.UpdatedCount,
		&i.FailedCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishResyncJob = `-- name: FinishResyncJob :one
UPDATE deck_resync_jobs
SET status = $1, error_message = $2, finished_at = now(), updated_at = now()
WHERE id = $3
RETURNING id, user_id, status, total_decks, updated_count, failed_count, error_message, created_at, updated_at, finished_at
`

type FinishResyncJobParams struct {
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) FinishResyncJob(ctx context.Context, arg FinishResyncJobParams) (DeckResyncJob, error) {
	row := q.db.QueryRow(ctx, finishResyncJob, arg.Status, arg.ErrorMessage, arg.ID)
	var i DeckResyncJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalDecks,
		&i.UpdatedCount,
		&i.FailedCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getResyncJob = `-- name: GetResyncJob :one
SELECT id, user_id, status, total_decks, updated_count, failed_count, error_message, created_at, updated_at, finished_at FROM deck_resync_jobs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetResyncJob(ctx context.Context, id pgtype.UUID) (DeckResyncJob, error) {
	row := q.db.QueryRow(ctx, getResyncJob, id)
	var i DeckResyncJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalDecks,
		&i.UpdatedCount,
		&i.FailedCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const reapStaleResyncJobs = `-- name: ReapStaleResyncJobs :many
UPDATE deck_resync_jobs
SET status = 'failed',
    error_message = 'Interrupted by a server restart before finishing; please retry the resync.',
    finished_at = now(),
    updated_at = now()
WHERE status IN ('pending', 'in_progress')
RETURNING id, user_id, status, total_decks, updated_count, failed_count, error_message, created_at, updated_at, finished_at
`

func (q *Queries) ReapStaleResyncJobs(ctx context.Context) ([]DeckResyncJob, error) {
	rows, err := q.db.Query(ctx, reapStaleResyncJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeckResyncJob
	for rows.Next() {
		var i DeckResyncJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalDecks,
			&i.UpdatedCount,
			&i.FailedCount,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordResyncJobDeckResult = `-- name: RecordResyncJobDeckResult :one
UPDATE deck_resync_jobs
SET updated_count = updated_count + $1::int,
    failed_count = failed_count + $2::int,
    updated_at = now()
WHERE id = $3
RETURNING id, user_id, status, total_decks, updated_count, failed_count, error_message, created_at, updated_at, finished_at
`

type RecordResyncJobDeckResultParams struct {
	UpdatedDelta int32       `json:"updated_delta"`
	FailedDelta  int32       `json:"failed_delta"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) RecordResyncJobDeckResult(ctx context.Context, arg RecordResyncJobDeckResultParams) (DeckResyncJob, error) {
	row := q.db.QueryRow(ctx, recordResyncJobDeckResult, arg.UpdatedDelta, arg.FailedDelta, arg.ID)
	var i DeckResyncJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalDecks,
		&i.UpdatedCount,
		&i.FailedCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}
