// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package deckresync

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateResyncJob(ctx context.Context, arg CreateResyncJobParams) (DeckResyncJob, error)
	FinishResyncJob(ctx context.Context, arg FinishResyncJobParams) (DeckResyncJob, error)
	GetResyncJob(ctx context.Context, id pgtype.UUID) (DeckResyncJob, error)
	RecordResyncJobDeckResult(ctx context.Context, arg RecordResyncJobDeckResultParams) (DeckResyncJob, error)
}

var _ Querier = (*Queries)(nil)
