// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package admin

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Global counts for the admin dashboard's home page. Live-computed on every
	// call, no summary table — same "live aggregation, no summary table" choice
	// already made for GetPlaygroupStats (internal/statistics); admin-panel
	// traffic is low enough that this doesn't need to be pre-aggregated.
	GetAdminOverviewStats(ctx context.Context) (GetAdminOverviewStatsRow, error)
	// A user's profile plus deck/games-played counts, for the admin user detail
	// screen. Counted with correlated subqueries instead of a JOIN + GROUP BY: at
	// one row per call this is simpler to read and just as cheap, and it avoids
	// fan-out duplicating the user's columns per matching deck/game_player row.
	GetUserDetail(ctx context.Context, id pgtype.UUID) (GetUserDetailRow, error)
	// Keyset pagination over (created_at, id) DESC, same scheme as
	// playgroups.ListPlaygroupsForUserPage (see internal/common/pagination.go). The
	// search filter reuses the same ILIKE-both-fields approach as
	// users.SearchUsersByUsername, but here it also matches email: this listing is
	// admin-only (see auth.RequireAdmin), so the "don't let email be enumerated by
	// partial match" concern that keeps users.SearchUsers email-exact-only doesn't apply.
	ListUsersPage(ctx context.Context, arg ListUsersPageParams) ([]User, error)
	UpdateUserActiveStatus(ctx context.Context, arg UpdateUserActiveStatusParams) (User, error)
}

var _ Querier = (*Queries)(nil)
