// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package admin

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminOverviewStats = `-- name: GetAdminOverviewStats :one
SELECT
  (SELECT count(*) FROM users) AS total_users,
  (SELECT count(*) FROM users WHERE is_active) AS active_users,
  (SELECT count(*) FROM users WHERE email_verified) AS verified_users,
  (SELECT count(*) FROM decks) AS total_decks,
  (SELECT count(*) FROM playgroups) AS total_playgroups,
  (SELECT count(*) FROM games WHERE status = 'finished') AS total_finished_games,
  (SELECT count(*) FROM tournaments) AS total_tournaments
`

type GetAdminOverviewStatsRow struct {
	TotalUsers         int64 `json:"total_users"`
	ActiveUsers        int64 `json:"active_users"`
	VerifiedUsers      int64 `json:"verified_users"`
	TotalDecks         int64 `json:"total_decks"`
	TotalPlaygroups    int64 `json:"total_playgroups"`
	TotalFinishedGames int64 `json:"total_finished_games"`
	TotalTournaments   int64 `json:"total_tournaments"`
}

// Global counts for the admin dashboard's home page. Live-computed on every
// call, no summary table — same "live aggregation, no summary table" choice
// already made for GetPlaygroupStats (internal/statistics); admin-panel
// traffic is low enough that this doesn't need to be pre-aggregated.
func (q *Queries) GetAdminOverviewStats(ctx context.Context) (GetAdminOverviewStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminOverviewStats)
	var i GetAdminOverviewStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.ActiveUsers,
		&i.VerifiedUsers,
		&i.TotalDecks,
		&i.TotalPlaygroups,
		&i.TotalFinishedGames,
		&i.TotalTournaments,
	)
	return i, err
}

const getUserDetail = `-- name: GetUserDetail :one
SELECT
  u.id, u.username, u.email, u.password_hash, u.created_at, u.updated_at, u.google_id, u.moxfield_username, u.email_verified, u.is_admin, u.is_active,
  (SELECT count(*) FROM decks d WHERE d.user_id = u.id) AS deck_count,
  (SELECT count(*) FROM game_players gp WHERE gp.user_id = u.id) AS games_played_count
FROM users u
WHERE u.id = $1
LIMIT 1
`

type GetUserDetailRow struct {
	ID               pgtype.UUID      `json:"id"`
	Username         string           `json:"username"`
	Email            string           `json:"email"`
	PasswordHash     pgtype.Text      `json:"password_hash"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	GoogleID         pgtype.Text      `json:"google_id"`
	MoxfieldUsername pgtype.Text      `json:"moxfield_username"`
	EmailVerified    bool             `json:"email_verified"`
	IsAdmin          bool             `json:"is_admin"`
	IsActive         bool             `json:"is_active"`
	DeckCount        int64            `json:"deck_count"`
	GamesPlayedCount int64            `json:"games_played_count"`
}

// A user's profile plus deck/games-played counts, for the admin user detail
// screen. Counted with correlated subqueries instead of a JOIN + GROUP BY: at
// one row per call this is simpler to read and just as cheap, and it avoids
// fan-out duplicating the user's columns per matching deck/game_player row.
func (q *Queries) GetUserDetail(ctx context.Context, id pgtype.UUID) (GetUserDetailRow, error) {
	row := q.db.QueryRow(ctx, getUserDetail, id)
	var i GetUserDetailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.IsActive,
		&i.DeckCount,
		&i.GamesPlayedCount,
	)
	return i, err
}

const listUsersPage = `-- name: ListUsersPage :many
SELECT id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified, is_admin, is_active FROM users
WHERE (
    $1::text IS NULL
    OR username ILIKE '%' || $1::text || '%'
    OR email ILIKE '%' || $1::text || '%'
  )
  AND (
    $2::timestamp IS NULL
    OR (created_at, id) < ($2::timestamp, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListUsersPageParams struct {
	Search          pgtype.Text      `json:"search"`
	CursorCreatedAt pgtype.Timestamp `json:"cursor_created_at"`
	CursorID        pgtype.UUID      `json:"cursor_id"`
	PageLimit       int32            `json:"page_limit"`
}

// Keyset pagination over (created_at, id) DESC, same scheme as
// playgroups.ListPlaygroupsForUserPage (see internal/common/pagination.go). The
// search filter reuses the same ILIKE-both-fields approach as
// users.SearchUsersByUsername, but here it also matches email: this listing is
// admin-only (see auth.RequireAdmin), so the "don't let email be enumerated by
// partial match" concern that keeps users.SearchUsers email-exact-only doesn't apply.
func (q *Queries) ListUsersPage(ctx context.Context, arg ListUsersPageParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersPage,
		arg.Search,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GoogleID,
			&i.MoxfieldUsername,
			&i.EmailVerified,
			&i.IsAdmin,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserActiveStatus = `-- name: UpdateUserActiveStatus :one
UPDATE users SET is_active = $2
WHERE id = $1
RETURNING id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified, is_admin, is_active
`

type UpdateUserActiveStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateUserActiveStatus(ctx context.Context, arg UpdateUserActiveStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserActiveStatus, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
		&i.IsAdmin,
		&i.IsActive,
	)
	return i, err
}
