// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package moxfieldimport

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateImportJob(ctx context.Context, arg CreateImportJobParams) (MoxfieldImportJob, error)
	FinishImportJob(ctx context.Context, arg FinishImportJobParams) (MoxfieldImportJob, error)
	GetImportJob(ctx context.Context, id pgtype.UUID) (MoxfieldImportJob, error)
	GetLatestImportJobByUser(ctx context.Context, userID pgtype.UUID) (MoxfieldImportJob, error)
	ReapStaleImportJobs(ctx context.Context) ([]MoxfieldImportJob, error)
	RecordImportJobDeckResult(ctx context.Context, arg RecordImportJobDeckResultParams) (MoxfieldImportJob, error)
	SetImportJobInProgress(ctx context.Context, arg SetImportJobInProgressParams) (MoxfieldImportJob, error)
}

var _ Querier = (*Queries)(nil)
