// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package moxfieldimport

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImportJob = `-- name: CreateImportJob :one
INSERT INTO moxfield_import_jobs (user_id, moxfield_username)
VALUES ($1, $2)
RETURNING id, user_id, moxfield_username, status, total_decks, imported_count, failed_count, error_message, created_at, updated_at, finished_at
`

type CreateImportJobParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	MoxfieldUsername string      `json:"moxfield_username"`
}

func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (MoxfieldImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob, arg.UserID, arg.MoxfieldUsername)
	var i MoxfieldImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MoxfieldUsername,
		&i.Status,
		&i.TotalDecks,
		&i.ImportedCount,
		&i.FailedCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishImportJob = `-- name: FinishImportJob :one
UPDATE moxfield_import_jobs
SET status = $1, error_message = $2, finished_at = now(), updated_at = now()
WHERE id = $3
RETURNING id, user_id, moxfield_username, status, total_decks, imported_count, failed_count, error_message, created_at, updated_at, finished_at
`

type FinishImportJobParams struct {
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) FinishImportJob(ctx context.Context, arg FinishImportJobParams) (MoxfieldImportJob, error) {
	row := q.db.QueryRow(ctx, finishImportJob, arg.Status, arg.ErrorMessage, arg.ID)
	var i MoxfieldImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MoxfieldUsername,
		&i.Status,
		&i.TotalDecks,
		&i.ImportedCount,
		&i.FailedCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getImportJob = `-- name: GetImportJob :one
SELECT id, user_id, moxfield_username, status, total_decks, imported_count, failed_count, error_message, created_at, updated_at, finished_at FROM moxfield_import_jobs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetImportJob(ctx context.Context, id pgtype.UUID) (MoxfieldImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJob, id)
	var i MoxfieldImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MoxfieldUsername,
		&i.Status,
		&i.TotalDecks,
		&i.ImportedCount,
		&i.FailedCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLatestImportJobByUser = `-- name: GetLatestImportJobByUser :one
SELECT id, user_id, moxfield_username, status, total_decks, imported_count, failed_count, error_message, created_at, updated_at, finished_at FROM moxfield_import_jobs WHERE user_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestImportJobByUser(ctx context.Context, userID pgtype.UUID) (MoxfieldImportJob, error) {
	row := q.db.QueryRow(ctx, getLatestImportJobByUser, userID)
	var i MoxfieldImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MoxfieldUsername,
		&i.Status,
		&i.TotalDecks,
		&i.ImportedCount,
		&i.FailedCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const recordImportJobDeckResult = `-- name: RecordImportJobDeckResult :one
UPDATE moxfield_import_jobs
SET imported_count = imported_count + $1::int,
    failed_count = failed_count + $2::int,
    updated_at = now()
WHERE id = $3
RETURNING id, user_id, moxfield_username, status, total_decks, imported_count, failed_count, error_message, created_at, updated_at, finished_at
`

type RecordImportJobDeckResultParams struct {
	ImportedDelta int32       `json:"imported_delta"`
	FailedDelta   int32       `json:"failed_delta"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) RecordImportJobDeckResult(ctx context.Context, arg RecordImportJobDeckResultParams) (MoxfieldImportJob, error) {
	row := q.db.QueryRow(ctx, recordImportJobDeckResult, arg.ImportedDelta, arg.FailedDelta, arg.ID)
	var i MoxfieldImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MoxfieldUsername,
		&i.Status,
		&i.TotalDecks,
		&i.ImportedCount,
		&i.FailedCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const setImportJobInProgress = `-- name: SetImportJobInProgress :one
UPDATE moxfield_import_jobs
SET status = 'in_progress', total_decks = $1, updated_at = now()
WHERE id = $2
RETURNING id, user_id, moxfield_username, status, total_decks, imported_count, failed_count, error_message, created_at, updated_at, finished_at
`

type SetImportJobInProgressParams struct {
	TotalDecks pgtype.Int4 `json:"total_decks"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) SetImportJobInProgress(ctx context.Context, arg SetImportJobInProgressParams) (MoxfieldImportJob, error) {
	row := q.db.QueryRow(ctx, setImportJobInProgress, arg.TotalDecks, arg.ID)
	var i MoxfieldImportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MoxfieldUsername,
		&i.Status,
		&i.TotalDecks,
		&i.ImportedCount,
		&i.FailedCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}
