// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package gameactions

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGameAction = `-- name: CreateGameAction :one
INSERT INTO game_actions (game_id, actor_id, target_id, action_type, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, game_id, actor_id, target_id, action_type, payload, created_at
`

type CreateGameActionParams struct {
	GameID     pgtype.UUID `json:"game_id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	TargetID   pgtype.UUID `json:"target_id"`
	ActionType string      `json:"action_type"`
	Payload    []byte      `json:"payload"`
}

func (q *Queries) CreateGameAction(ctx context.Context, arg CreateGameActionParams) (GameAction, error) {
	row := q.db.QueryRow(ctx, createGameAction,
		arg.GameID,
		arg.ActorID,
		arg.TargetID,
		arg.ActionType,
		arg.Payload,
	)
	var i GameAction
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.ActorID,
		&i.TargetID,
		&i.ActionType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listGameActions = `-- name: ListGameActions :many
SELECT id, game_id, actor_id, target_id, action_type, payload, created_at FROM game_actions WHERE game_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListGameActions(ctx context.Context, gameID pgtype.UUID) ([]GameAction, error) {
	rows, err := q.db.Query(ctx, listGameActions, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameAction
	for rows.Next() {
		var i GameAction
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.ActorID,
			&i.TargetID,
			&i.ActionType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
