// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gameactions

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateGameAction(ctx context.Context, arg CreateGameActionParams) (GameAction, error)
	ListGameActions(ctx context.Context, gameID pgtype.UUID) ([]GameAction, error)
}

var _ Querier = (*Queries)(nil)
