// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package games

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGamePlayer = `-- name: AddGamePlayer :one
INSERT INTO game_players (game_id, user_id, deck_id)
VALUES ($1, $2, $3)
RETURNING id, game_id, user_id, deck_id, life_total, poison_counters, energy_counters, experience_counters, is_eliminated
`

type AddGamePlayerParams struct {
	GameID pgtype.UUID `json:"game_id"`
	UserID pgtype.UUID `json:"user_id"`
	DeckID pgtype.UUID `json:"deck_id"`
}

func (q *Queries) AddGamePlayer(ctx context.Context, arg AddGamePlayerParams) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, addGamePlayer, arg.GameID, arg.UserID, arg.DeckID)
	var i GamePlayer
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.DeckID,
		&i.LifeTotal,
		&i.PoisonCounters,
		&i.EnergyCounters,
		&i.ExperienceCounters,
		&i.IsEliminated,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (playgroup_id, status)
VALUES ($1, $2)
RETURNING id, playgroup_id, status, started_at, finished_at, created_at
`

type CreateGameParams struct {
	PlaygroupID pgtype.UUID `json:"playgroup_id"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.PlaygroupID, arg.Status)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlaygroupID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const finishGame = `-- name: FinishGame :one
UPDATE games
SET status = 'finished', finished_at = now()
WHERE id = $1
RETURNING id, playgroup_id, status, started_at, finished_at, created_at
`

func (q *Queries) FinishGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, finishGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlaygroupID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT id, playgroup_id, status, started_at, finished_at, created_at FROM games WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlaygroupID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listGamePlayers = `-- name: ListGamePlayers :many
SELECT id, game_id, user_id, deck_id, life_total, poison_counters, energy_counters, experience_counters, is_eliminated FROM game_players WHERE game_id = $1
`

func (q *Queries) ListGamePlayers(ctx context.Context, gameID pgtype.UUID) ([]GamePlayer, error) {
	rows, err := q.db.Query(ctx, listGamePlayers, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePlayer
	for rows.Next() {
		var i GamePlayer
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.DeckID,
			&i.LifeTotal,
			&i.PoisonCounters,
			&i.EnergyCounters,
			&i.ExperienceCounters,
			&i.IsEliminated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGames = `-- name: ListGames :many
SELECT id, playgroup_id, status, started_at, finished_at, created_at FROM games ORDER BY created_at DESC
`

func (q *Queries) ListGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.PlaygroupID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGamePlayer = `-- name: RemoveGamePlayer :exec
DELETE FROM game_players WHERE game_id = $1 AND user_id = $2
`

type RemoveGamePlayerParams struct {
	GameID pgtype.UUID `json:"game_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveGamePlayer(ctx context.Context, arg RemoveGamePlayerParams) error {
	_, err := q.db.Exec(ctx, removeGamePlayer, arg.GameID, arg.UserID)
	return err
}

const startGame = `-- name: StartGame :one
UPDATE games
SET status = 'active', started_at = now()
WHERE id = $1
RETURNING id, playgroup_id, status, started_at, finished_at, created_at
`

func (q *Queries) StartGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, startGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlaygroupID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
