// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package games

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGamePlayer = `-- name: AddGamePlayer :one
INSERT INTO game_players (game_id, user_id, deck_id, added_by)
VALUES ($1, $2, $3, $4)
RETURNING id, game_id, user_id, deck_id, life_total, poison_counters, energy_counters, experience_counters, is_eliminated, added_by
`

type AddGamePlayerParams struct {
	GameID  pgtype.UUID `json:"game_id"`
	UserID  pgtype.UUID `json:"user_id"`
	DeckID  pgtype.UUID `json:"deck_id"`
	AddedBy pgtype.UUID `json:"added_by"`
}

func (q *Queries) AddGamePlayer(ctx context.Context, arg AddGamePlayerParams) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, addGamePlayer,
		arg.GameID,
		arg.UserID,
		arg.DeckID,
		arg.AddedBy,
	)
	var i GamePlayer
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.DeckID,
		&i.LifeTotal,
		&i.PoisonCounters,
		&i.EnergyCounters,
		&i.ExperienceCounters,
		&i.IsEliminated,
		&i.AddedBy,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (playgroup_id, status)
VALUES ($1, $2)
RETURNING id, playgroup_id, status, started_at, finished_at, created_at, current_turn_player_id
`

type CreateGameParams struct {
	PlaygroupID pgtype.UUID `json:"playgroup_id"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.PlaygroupID, arg.Status)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlaygroupID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.CurrentTurnPlayerID,
	)
	return i, err
}

const finishGame = `-- name: FinishGame :one
UPDATE games
SET status = 'finished', finished_at = now()
WHERE id = $1
RETURNING id, playgroup_id, status, started_at, finished_at, created_at, current_turn_player_id
`

func (q *Queries) FinishGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, finishGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlaygroupID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.CurrentTurnPlayerID,
	)
	return i, err
}

const getDeckByID = `-- name: GetDeckByID :one
SELECT id, user_id, name, commander, moxfield_id, created_at, updated_at, image_url FROM decks WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDeckByID(ctx context.Context, id pgtype.UUID) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckByID, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Commander,
		&i.MoxfieldID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT id, playgroup_id, status, started_at, finished_at, created_at, current_turn_player_id FROM games WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlaygroupID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.CurrentTurnPlayerID,
	)
	return i, err
}

const listGamePlayers = `-- name: ListGamePlayers :many
SELECT id, game_id, user_id, deck_id, life_total, poison_counters, energy_counters, experience_counters, is_eliminated, added_by FROM game_players WHERE game_id = $1
`

func (q *Queries) ListGamePlayers(ctx context.Context, gameID pgtype.UUID) ([]GamePlayer, error) {
	rows, err := q.db.Query(ctx, listGamePlayers, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePlayer
	for rows.Next() {
		var i GamePlayer
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.DeckID,
			&i.LifeTotal,
			&i.PoisonCounters,
			&i.EnergyCounters,
			&i.ExperienceCounters,
			&i.IsEliminated,
			&i.AddedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesForPlaygroup = `-- name: ListGamesForPlaygroup :many
SELECT id, playgroup_id, status, started_at, finished_at, created_at, current_turn_player_id FROM games WHERE playgroup_id = $1 ORDER BY created_at DESC
`

// Historial de partidas de un grupo. Sin paginar: acotado a un solo playgroup,
// nunca se acerca al volumen de ListGamesPage (el historial global).
func (q *Queries) ListGamesForPlaygroup(ctx context.Context, playgroupID pgtype.UUID) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesForPlaygroup, playgroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.PlaygroupID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.CurrentTurnPlayerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesPage = `-- name: ListGamesPage :many
SELECT id, playgroup_id, status, started_at, finished_at, created_at, current_turn_player_id FROM games
WHERE (
    $1::timestamp IS NULL
    OR (created_at, id) < ($1::timestamp, $2::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListGamesPageParams struct {
	CursorCreatedAt pgtype.Timestamp `json:"cursor_created_at"`
	CursorID        pgtype.UUID      `json:"cursor_id"`
	PageLimit       int32            `json:"page_limit"`
}

// Paginación keyset sobre (created_at, id) DESC. Con cursor_created_at NULL
// devuelve la primera página; con cursor, las filas estrictamente posteriores en
// el orden de la lista. Ver internal/common/pagination.go.
func (q *Queries) ListGamesPage(ctx context.Context, arg ListGamesPageParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesPage, arg.CursorCreatedAt, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.PlaygroupID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.CurrentTurnPlayerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGamePlayer = `-- name: RemoveGamePlayer :exec
DELETE FROM game_players WHERE game_id = $1 AND user_id = $2
`

type RemoveGamePlayerParams struct {
	GameID pgtype.UUID `json:"game_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveGamePlayer(ctx context.Context, arg RemoveGamePlayerParams) error {
	_, err := q.db.Exec(ctx, removeGamePlayer, arg.GameID, arg.UserID)
	return err
}

const startGame = `-- name: StartGame :one
UPDATE games
SET status = 'active', started_at = now()
WHERE id = $1
RETURNING id, playgroup_id, status, started_at, finished_at, created_at, current_turn_player_id
`

func (q *Queries) StartGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, startGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlaygroupID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.CurrentTurnPlayerID,
	)
	return i, err
}
