// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package games

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGamePlayer = `-- name: AddGamePlayer :one
INSERT INTO game_players (game_id, user_id, deck_id, added_by)
VALUES ($1, $2, $3, $4)
RETURNING id, game_id, user_id, deck_id, life_total, poison_counters, energy_counters, experience_counters, is_eliminated, added_by
`

type AddGamePlayerParams struct {
	GameID  pgtype.UUID `json:"game_id"`
	UserID  pgtype.UUID `json:"user_id"`
	DeckID  pgtype.UUID `json:"deck_id"`
	AddedBy pgtype.UUID `json:"added_by"`
}

func (q *Queries) AddGamePlayer(ctx context.Context, arg AddGamePlayerParams) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, addGamePlayer,
		arg.GameID,
		arg.UserID,
		arg.DeckID,
		arg.AddedBy,
	)
	var i GamePlayer
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.UserID,
		&i.DeckID,
		&i.LifeTotal,
		&i.PoisonCounters,
		&i.EnergyCounters,
		&i.ExperienceCounters,
		&i.IsEliminated,
		&i.AddedBy,
	)
	return i, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (playgroup_id, status)
VALUES ($1, $2)
RETURNING id, playgroup_id, status, started_at, finished_at, created_at, current_turn_player_id
`

type CreateGameParams struct {
	PlaygroupID pgtype.UUID `json:"playgroup_id"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.PlaygroupID, arg.Status)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlaygroupID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.CurrentTurnPlayerID,
	)
	return i, err
}

const finishGame = `-- name: FinishGame :one
UPDATE games
SET status = 'finished', finished_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, playgroup_id, status, started_at, finished_at, created_at, current_turn_player_id
`

// The "AND status = 'active'" guard is load-bearing, not decorative: without
// it, N concurrent FinishGame calls on the same game (e.g. two players
// tapping "Finish" at once) all pass the service's earlier status check,
// all succeed here, and each one separately triggers
// statistics.RecalculateForGame — which is purely additive (ON CONFLICT DO
// UPDATE SET games_played = games_played + EXCLUDED.games_played), so
// games_played/games_won/etc. end up multiplied by however many calls
// raced. With the guard, only the first UPDATE actually matches a row; the
// rest affect 0 rows and the service maps that to ErrGameNotActive (409).
func (q *Queries) FinishGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, finishGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlaygroupID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.CurrentTurnPlayerID,
	)
	return i, err
}

const getDeckByID = `-- name: GetDeckByID :one
SELECT id, user_id, name, commander, moxfield_id, created_at, updated_at, image_url FROM decks WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDeckByID(ctx context.Context, id pgtype.UUID) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckByID, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Commander,
		&i.MoxfieldID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT id, playgroup_id, status, started_at, finished_at, created_at, current_turn_player_id FROM games WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlaygroupID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.CurrentTurnPlayerID,
	)
	return i, err
}

const listGamePlayers = `-- name: ListGamePlayers :many
SELECT id, game_id, user_id, deck_id, life_total, poison_counters, energy_counters, experience_counters, is_eliminated, added_by FROM game_players WHERE game_id = $1
`

func (q *Queries) ListGamePlayers(ctx context.Context, gameID pgtype.UUID) ([]GamePlayer, error) {
	rows, err := q.db.Query(ctx, listGamePlayers, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePlayer
	for rows.Next() {
		var i GamePlayer
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.DeckID,
			&i.LifeTotal,
			&i.PoisonCounters,
			&i.EnergyCounters,
			&i.ExperienceCounters,
			&i.IsEliminated,
			&i.AddedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamePlayersForGames = `-- name: ListGamePlayersForGames :many
SELECT id, game_id, user_id, deck_id, life_total, poison_counters, energy_counters, experience_counters, is_eliminated, added_by FROM game_players WHERE game_id = ANY($1::uuid[])
`

// Every seat across a whole list of games in one round trip, for callers that
// need the players of all of them (ListGamesForPlaygroup) instead of one game's.
// Same game_id = ANY(...) shape as statistics.ListPlayersForGames.
func (q *Queries) ListGamePlayersForGames(ctx context.Context, gameIds []pgtype.UUID) ([]GamePlayer, error) {
	rows, err := q.db.Query(ctx, listGamePlayersForGames, gameIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePlayer
	for rows.Next() {
		var i GamePlayer
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.UserID,
			&i.DeckID,
			&i.LifeTotal,
			&i.PoisonCounters,
			&i.EnergyCounters,
			&i.ExperienceCounters,
			&i.IsEliminated,
			&i.AddedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesForPlaygroup = `-- name: ListGamesForPlaygroup :many
SELECT id, playgroup_id, status, started_at, finished_at, created_at, current_turn_player_id FROM games WHERE playgroup_id = $1 ORDER BY created_at DESC
`

// Game history for a group. Unpaginated: scoped to a single playgroup,
// never approaches the volume of ListGamesPage (the global history).
func (q *Queries) ListGamesForPlaygroup(ctx context.Context, playgroupID pgtype.UUID) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesForPlaygroup, playgroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.PlaygroupID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.CurrentTurnPlayerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesPage = `-- name: ListGamesPage :many
SELECT games.id, games.playgroup_id, games.status, games.started_at, games.finished_at, games.created_at, games.current_turn_player_id FROM games
WHERE EXISTS (
    SELECT 1 FROM game_players gp
    WHERE gp.game_id = games.id AND gp.user_id = $1::uuid
  )
  AND (
    $2::timestamp IS NULL
    OR (created_at, id) < ($2::timestamp, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListGamesPageParams struct {
	UserID          pgtype.UUID      `json:"user_id"`
	CursorCreatedAt pgtype.Timestamp `json:"cursor_created_at"`
	CursorID        pgtype.UUID      `json:"cursor_id"`
	PageLimit       int32            `json:"page_limit"`
}

// Keyset pagination over (created_at, id) DESC, scoped to games where the
// authenticated user has (or had) a seat — never the full cross-tenant
// history. With cursor_created_at NULL it returns the first page; with a
// cursor, the rows strictly after it in list order. See internal/common/pagination.go.
func (q *Queries) ListGamesPage(ctx context.Context, arg ListGamesPageParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesPage,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.PlaygroupID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.CurrentTurnPlayerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGamePlayer = `-- name: RemoveGamePlayer :exec
DELETE FROM game_players WHERE game_id = $1 AND user_id = $2
`

type RemoveGamePlayerParams struct {
	GameID pgtype.UUID `json:"game_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveGamePlayer(ctx context.Context, arg RemoveGamePlayerParams) error {
	_, err := q.db.Exec(ctx, removeGamePlayer, arg.GameID, arg.UserID)
	return err
}

const startGame = `-- name: StartGame :one
UPDATE games
SET status = 'active', started_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, playgroup_id, status, started_at, finished_at, created_at, current_turn_player_id
`

// The "AND status = 'pending'" guard makes the pending->active transition
// atomic: without it, two concurrent StartGame calls both read status as
// pending before either writes, and both succeed. See FinishGame below for
// the same race with a worse consequence (double-counted statistics).
func (q *Queries) StartGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, startGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.PlaygroupID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.CurrentTurnPlayerID,
	)
	return i, err
}
