// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package games

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddGamePlayer(ctx context.Context, arg AddGamePlayerParams) (GamePlayer, error)
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	FinishGame(ctx context.Context, id pgtype.UUID) (Game, error)
	GetDeckByID(ctx context.Context, id pgtype.UUID) (Deck, error)
	GetGame(ctx context.Context, id pgtype.UUID) (Game, error)
	ListGamePlayers(ctx context.Context, gameID pgtype.UUID) ([]GamePlayer, error)
	// Game history for a group. Unpaginated: scoped to a single playgroup,
	// never approaches the volume of ListGamesPage (the global history).
	ListGamesForPlaygroup(ctx context.Context, playgroupID pgtype.UUID) ([]Game, error)
	// Keyset pagination over (created_at, id) DESC. With cursor_created_at NULL
	// it returns the first page; with a cursor, the rows strictly after it in
	// list order. See internal/common/pagination.go.
	ListGamesPage(ctx context.Context, arg ListGamesPageParams) ([]Game, error)
	RemoveGamePlayer(ctx context.Context, arg RemoveGamePlayerParams) error
	StartGame(ctx context.Context, id pgtype.UUID) (Game, error)
}

var _ Querier = (*Queries)(nil)
