// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package playgroups

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPlaygroupMember(ctx context.Context, arg AddPlaygroupMemberParams) (PlaygroupMember, error)
	CountPlaygroupMembers(ctx context.Context, playgroupID pgtype.UUID) (int64, error)
	CreatePlaygroup(ctx context.Context, arg CreatePlaygroupParams) (Playgroup, error)
	// No ON DELETE CASCADE from games (see 00001_initial_schema.sql): a group that
	// has any game, in any status, makes this fail with games_playgroup_id_fkey,
	// which is exactly the "only an empty group can be deleted" rule (see
	// Service.DeletePlaygroup).
	DeletePlaygroup(ctx context.Context, id pgtype.UUID) error
	DeletePlaygroupMembers(ctx context.Context, playgroupID pgtype.UUID) error
	GetPlaygroup(ctx context.Context, id pgtype.UUID) (Playgroup, error)
	GetPlaygroupByInviteCode(ctx context.Context, inviteCode pgtype.Text) (Playgroup, error)
	GetPlaygroupMember(ctx context.Context, arg GetPlaygroupMemberParams) (PlaygroupMember, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// A user's decks, for the "which deck are they playing" picker when proxy-joining
	// a fellow group member (see ADR-0013). Authorization (does the caller share a
	// playgroup with this user?) is done by the service, not this query.
	ListDecksByUserID(ctx context.Context, userID pgtype.UUID) ([]Deck, error)
	ListPlaygroupMembers(ctx context.Context, playgroupID pgtype.UUID) ([]ListPlaygroupMembersRow, error)
	ListPlaygroups(ctx context.Context) ([]Playgroup, error)
	ListPlaygroupsForUser(ctx context.Context, userID pgtype.UUID) ([]Playgroup, error)
	// Keyset pagination over (created_at, id) DESC, scoped to playgroups the user is
	// a member of (same shape as games.ListGamesPage). With cursor_created_at NULL
	// it returns the first page; with a cursor, the rows strictly after it in list
	// order. See internal/common/pagination.go.
	ListPlaygroupsForUserPage(ctx context.Context, arg ListPlaygroupsForUserPageParams) ([]Playgroup, error)
	// Rotating and revoking are the same write: a new code, or NULL.
	SetPlaygroupInviteCode(ctx context.Context, arg SetPlaygroupInviteCodeParams) (Playgroup, error)
	UpdatePlaygroupName(ctx context.Context, arg UpdatePlaygroupNameParams) (Playgroup, error)
}

var _ Querier = (*Queries)(nil)
