// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package playgroups

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlaygroupMember = `-- name: AddPlaygroupMember :one
INSERT INTO playgroup_members (playgroup_id, user_id)
VALUES ($1, $2)
RETURNING playgroup_id, user_id, joined_at
`

type AddPlaygroupMemberParams struct {
	PlaygroupID pgtype.UUID `json:"playgroup_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddPlaygroupMember(ctx context.Context, arg AddPlaygroupMemberParams) (PlaygroupMember, error) {
	row := q.db.QueryRow(ctx, addPlaygroupMember, arg.PlaygroupID, arg.UserID)
	var i PlaygroupMember
	err := row.Scan(&i.PlaygroupID, &i.UserID, &i.JoinedAt)
	return i, err
}

const createPlaygroup = `-- name: CreatePlaygroup :one
INSERT INTO playgroups (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreatePlaygroup(ctx context.Context, name string) (Playgroup, error) {
	row := q.db.QueryRow(ctx, createPlaygroup, name)
	var i Playgroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaygroup = `-- name: GetPlaygroup :one
SELECT id, name, created_at, updated_at FROM playgroups WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlaygroup(ctx context.Context, id pgtype.UUID) (Playgroup, error) {
	row := q.db.QueryRow(ctx, getPlaygroup, id)
	var i Playgroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaygroupMember = `-- name: GetPlaygroupMember :one
SELECT playgroup_id, user_id, joined_at FROM playgroup_members WHERE playgroup_id = $1 AND user_id = $2 LIMIT 1
`

type GetPlaygroupMemberParams struct {
	PlaygroupID pgtype.UUID `json:"playgroup_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetPlaygroupMember(ctx context.Context, arg GetPlaygroupMemberParams) (PlaygroupMember, error) {
	row := q.db.QueryRow(ctx, getPlaygroupMember, arg.PlaygroupID, arg.UserID)
	var i PlaygroupMember
	err := row.Scan(&i.PlaygroupID, &i.UserID, &i.JoinedAt)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, created_at, updated_at, google_id, moxfield_username, email_verified FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleID,
		&i.MoxfieldUsername,
		&i.EmailVerified,
	)
	return i, err
}

const listDecksByUserID = `-- name: ListDecksByUserID :many
SELECT id, user_id, name, commander, moxfield_id, created_at, updated_at, image_url FROM decks WHERE user_id = $1 ORDER BY created_at DESC
`

// A user's decks, for the "which deck are they playing" picker when proxy-joining
// a fellow group member (see ADR-0013). Authorization (does the caller share a
// playgroup with this user?) is done by the service, not this query.
func (q *Queries) ListDecksByUserID(ctx context.Context, userID pgtype.UUID) ([]Deck, error) {
	rows, err := q.db.Query(ctx, listDecksByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Commander,
			&i.MoxfieldID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaygroupMembers = `-- name: ListPlaygroupMembers :many
SELECT pm.playgroup_id, pm.user_id, pm.joined_at, u.username
FROM playgroup_members pm
JOIN users u ON u.id = pm.user_id
WHERE pm.playgroup_id = $1
`

type ListPlaygroupMembersRow struct {
	PlaygroupID pgtype.UUID      `json:"playgroup_id"`
	UserID      pgtype.UUID      `json:"user_id"`
	JoinedAt    pgtype.Timestamp `json:"joined_at"`
	Username    string           `json:"username"`
}

func (q *Queries) ListPlaygroupMembers(ctx context.Context, playgroupID pgtype.UUID) ([]ListPlaygroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listPlaygroupMembers, playgroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaygroupMembersRow
	for rows.Next() {
		var i ListPlaygroupMembersRow
		if err := rows.Scan(
			&i.PlaygroupID,
			&i.UserID,
			&i.JoinedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaygroups = `-- name: ListPlaygroups :many
SELECT id, name, created_at, updated_at FROM playgroups ORDER BY created_at DESC
`

func (q *Queries) ListPlaygroups(ctx context.Context) ([]Playgroup, error) {
	rows, err := q.db.Query(ctx, listPlaygroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playgroup
	for rows.Next() {
		var i Playgroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaygroupsForUser = `-- name: ListPlaygroupsForUser :many
SELECT p.id, p.name, p.created_at, p.updated_at FROM playgroups p
JOIN playgroup_members pm ON pm.playgroup_id = p.id
WHERE pm.user_id = $1
ORDER BY p.created_at DESC
`

func (q *Queries) ListPlaygroupsForUser(ctx context.Context, userID pgtype.UUID) ([]Playgroup, error) {
	rows, err := q.db.Query(ctx, listPlaygroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playgroup
	for rows.Next() {
		var i Playgroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlaygroupName = `-- name: UpdatePlaygroupName :one
UPDATE playgroups SET name = $2
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdatePlaygroupNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdatePlaygroupName(ctx context.Context, arg UpdatePlaygroupNameParams) (Playgroup, error) {
	row := q.db.QueryRow(ctx, updatePlaygroupName, arg.ID, arg.Name)
	var i Playgroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
