// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package playgroups

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPlaygroupMember(ctx context.Context, arg AddPlaygroupMemberParams) (PlaygroupMember, error)
	CreatePlaygroup(ctx context.Context, name string) (Playgroup, error)
	GetPlaygroup(ctx context.Context, id pgtype.UUID) (Playgroup, error)
	GetPlaygroupMember(ctx context.Context, arg GetPlaygroupMemberParams) (PlaygroupMember, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// A user's decks, for the "which deck are they playing" picker when proxy-joining
	// a fellow group member (see ADR-0013). Authorization (does the caller share a
	// playgroup with this user?) is done by the service, not this query.
	ListDecksByUserID(ctx context.Context, userID pgtype.UUID) ([]Deck, error)
	ListPlaygroupMembers(ctx context.Context, playgroupID pgtype.UUID) ([]ListPlaygroupMembersRow, error)
	ListPlaygroups(ctx context.Context) ([]Playgroup, error)
	ListPlaygroupsForUser(ctx context.Context, userID pgtype.UUID) ([]Playgroup, error)
	UpdatePlaygroupName(ctx context.Context, arg UpdatePlaygroupNameParams) (Playgroup, error)
}

var _ Querier = (*Queries)(nil)
