// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package playgroups

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlaygroupMember = `-- name: AddPlaygroupMember :one
INSERT INTO playgroup_members (playgroup_id, user_id)
VALUES ($1, $2)
RETURNING playgroup_id, user_id, joined_at
`

type AddPlaygroupMemberParams struct {
	PlaygroupID pgtype.UUID `json:"playgroup_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddPlaygroupMember(ctx context.Context, arg AddPlaygroupMemberParams) (PlaygroupMember, error) {
	row := q.db.QueryRow(ctx, addPlaygroupMember, arg.PlaygroupID, arg.UserID)
	var i PlaygroupMember
	err := row.Scan(&i.PlaygroupID, &i.UserID, &i.JoinedAt)
	return i, err
}

const createPlaygroup = `-- name: CreatePlaygroup :one
INSERT INTO playgroups (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreatePlaygroup(ctx context.Context, name string) (Playgroup, error) {
	row := q.db.QueryRow(ctx, createPlaygroup, name)
	var i Playgroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaygroup = `-- name: GetPlaygroup :one
SELECT id, name, created_at, updated_at FROM playgroups WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlaygroup(ctx context.Context, id pgtype.UUID) (Playgroup, error) {
	row := q.db.QueryRow(ctx, getPlaygroup, id)
	var i Playgroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlaygroupMembers = `-- name: ListPlaygroupMembers :many
SELECT playgroup_id, user_id, joined_at FROM playgroup_members WHERE playgroup_id = $1
`

func (q *Queries) ListPlaygroupMembers(ctx context.Context, playgroupID pgtype.UUID) ([]PlaygroupMember, error) {
	rows, err := q.db.Query(ctx, listPlaygroupMembers, playgroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaygroupMember
	for rows.Next() {
		var i PlaygroupMember
		if err := rows.Scan(&i.PlaygroupID, &i.UserID, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaygroups = `-- name: ListPlaygroups :many
SELECT id, name, created_at, updated_at FROM playgroups ORDER BY created_at DESC
`

func (q *Queries) ListPlaygroups(ctx context.Context) ([]Playgroup, error) {
	rows, err := q.db.Query(ctx, listPlaygroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playgroup
	for rows.Next() {
		var i Playgroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
