// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package decks

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (user_id, name, commander, moxfield_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, commander, moxfield_id, created_at, updated_at
`

type CreateDeckParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Name       string      `json:"name"`
	Commander  string      `json:"commander"`
	MoxfieldID pgtype.Text `json:"moxfield_id"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, createDeck,
		arg.UserID,
		arg.Name,
		arg.Commander,
		arg.MoxfieldID,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Commander,
		&i.MoxfieldID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :exec
DELETE FROM decks WHERE id = $1
`

func (q *Queries) DeleteDeck(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeck, id)
	return err
}

const getDeck = `-- name: GetDeck :one
SELECT id, user_id, name, commander, moxfield_id, created_at, updated_at FROM decks WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDeck(ctx context.Context, id pgtype.UUID) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeck, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Commander,
		&i.MoxfieldID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDecks = `-- name: ListDecks :many
SELECT id, user_id, name, commander, moxfield_id, created_at, updated_at FROM decks WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDecks(ctx context.Context, userID pgtype.UUID) ([]Deck, error) {
	rows, err := q.db.Query(ctx, listDecks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Commander,
			&i.MoxfieldID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
