// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package decks

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Copies the deck's current bracket and color identity onto its past seats
	// that had none when the game was played, and flags them as backfilled. A
	// backfilled seat keeps following the deck on every later change (its value
	// was a guess, and a mistake typed in must stay correctable); a seat that got
	// its value when it sat down keeps it: that's what was actually played.
	// Each field is handled on its own, since a seat can have one and not the other.
	// (On the right-hand side of SET, the columns read their pre-update values.)
	BackfillSeatDeckTraits(ctx context.Context, arg BackfillSeatDeckTraitsParams) error
	CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error)
	DeleteDeck(ctx context.Context, id pgtype.UUID) error
	GetDeck(ctx context.Context, id pgtype.UUID) (Deck, error)
	// Resolves a user's already-imported deck from its public Moxfield ID
	// (see internal/sync). The same Moxfield deck can be imported by several
	// users, hence the filter by user_id.
	GetDeckByMoxfieldID(ctx context.Context, arg GetDeckByMoxfieldIDParams) (Deck, error)
	// Keyset pagination over (created_at, id) DESC. With cursor_created_at NULL
	// it returns the first page; with a cursor, the rows strictly after it in
	// list order. See internal/common/pagination.go.
	//
	// brackets/colors narrow the list (NULL = no filter, see
	// common.DeckTraitFilter); a deck whose value is unknown never matches.
	// "exact" is containment both ways, so it doesn't depend on letter order.
	ListDecksPage(ctx context.Context, arg ListDecksPageParams) ([]Deck, error)
	// Re-syncs name, commander, image, bracket and color identity for an
	// already-imported deck with what Moxfield returns today (see internal/sync).
	// A bracket/color identity set by hand (the *_overridden flags) is kept.
	// updated_at marks the last successful sync.
	UpdateDeckFromMoxfield(ctx context.Context, arg UpdateDeckFromMoxfieldParams) (Deck, error)
	// Writes a deck's bracket and color identity with their override flags as
	// decks.Service.UpdateDeck resolved them. Doesn't touch updated_at: that one
	// means "last Moxfield sync".
	UpdateDeckTraits(ctx context.Context, arg UpdateDeckTraitsParams) (Deck, error)
}

var _ Querier = (*Queries)(nil)
