// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package decks

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (user_id, name, commander, moxfield_id, image_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, commander, moxfield_id, created_at, updated_at, image_url
`

type CreateDeckParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Name       string      `json:"name"`
	Commander  string      `json:"commander"`
	MoxfieldID pgtype.Text `json:"moxfield_id"`
	ImageUrl   pgtype.Text `json:"image_url"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, createDeck,
		arg.UserID,
		arg.Name,
		arg.Commander,
		arg.MoxfieldID,
		arg.ImageUrl,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Commander,
		&i.MoxfieldID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :exec
DELETE FROM decks WHERE id = $1
`

func (q *Queries) DeleteDeck(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeck, id)
	return err
}

const getDeck = `-- name: GetDeck :one
SELECT id, user_id, name, commander, moxfield_id, created_at, updated_at, image_url FROM decks WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDeck(ctx context.Context, id pgtype.UUID) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeck, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Commander,
		&i.MoxfieldID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const getDeckByMoxfieldID = `-- name: GetDeckByMoxfieldID :one
SELECT id, user_id, name, commander, moxfield_id, created_at, updated_at, image_url FROM decks
WHERE user_id = $1 AND moxfield_id = $2
ORDER BY created_at ASC
LIMIT 1
`

type GetDeckByMoxfieldIDParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	MoxfieldID pgtype.Text `json:"moxfield_id"`
}

// Resolves a user's already-imported deck from its public Moxfield ID
// (see internal/sync). The same Moxfield deck can be imported by several
// users, hence the filter by user_id.
func (q *Queries) GetDeckByMoxfieldID(ctx context.Context, arg GetDeckByMoxfieldIDParams) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeckByMoxfieldID, arg.UserID, arg.MoxfieldID)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Commander,
		&i.MoxfieldID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}

const listDecksPage = `-- name: ListDecksPage :many
SELECT id, user_id, name, commander, moxfield_id, created_at, updated_at, image_url FROM decks
WHERE user_id = $1
  AND (
    $2::timestamp IS NULL
    OR (created_at, id) < ($2::timestamp, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListDecksPageParams struct {
	UserID          pgtype.UUID      `json:"user_id"`
	CursorCreatedAt pgtype.Timestamp `json:"cursor_created_at"`
	CursorID        pgtype.UUID      `json:"cursor_id"`
	PageLimit       int32            `json:"page_limit"`
}

// Keyset pagination over (created_at, id) DESC. With cursor_created_at NULL
// it returns the first page; with a cursor, the rows strictly after it in
// list order. See internal/common/pagination.go.
func (q *Queries) ListDecksPage(ctx context.Context, arg ListDecksPageParams) ([]Deck, error) {
	rows, err := q.db.Query(ctx, listDecksPage,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Commander,
			&i.MoxfieldID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeckFromMoxfield = `-- name: UpdateDeckFromMoxfield :one
UPDATE decks
SET name = $2, commander = $3, image_url = $4, updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, commander, moxfield_id, created_at, updated_at, image_url
`

type UpdateDeckFromMoxfieldParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Commander string      `json:"commander"`
	ImageUrl  pgtype.Text `json:"image_url"`
}

// Re-syncs name, commander, and image for an already-imported deck with what
// Moxfield returns today (see internal/sync). updated_at marks the last successful sync.
func (q *Queries) UpdateDeckFromMoxfield(ctx context.Context, arg UpdateDeckFromMoxfieldParams) (Deck, error) {
	row := q.db.QueryRow(ctx, updateDeckFromMoxfield,
		arg.ID,
		arg.Name,
		arg.Commander,
		arg.ImageUrl,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Commander,
		&i.MoxfieldID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ImageUrl,
	)
	return i, err
}
